

;
; +-------------------------------------------------------------------------+
; |   This file has been generated by The Interactive Disassembler (IDA)    |
; |           Copyright (c) 2018 Hex-Rays, <support@hex-rays.com>           |
; |                            Freeware version                             |
; +-------------------------------------------------------------------------+
;
; Input SHA256 : 1A4A50467ACF78E594555F8C3EE6FFB06D28D8D99470FF78C962F37A84F74A90
; Input MD5    : B83191A4F927EAD37EBF9BFA2DE66A29
; Input CRC32  : F93F2EAC

; File Name   : C:\Users\guyma\Downloads\Package.exe
; Format      : Portable executable for 80386 (PE)
; Imagebase   : 400000
; Timestamp   : 5DDAF8C8 (Sun Nov 24 21:40:24 2019)
; Section 1. (virtual address 00001000)
; Virtual size                  : 0000F000 (  61440.)
; Section size in file          : 00000000 (      0.)
; Offset to raw data for section: 00000200
; Flags E0000080: Bss Executable Readable Writable
; Alignment     : default

.686p
.mmx
.model flat


; Segment type: Pure code
; Segment permissions: Read/Write/Execute
UPX0 segment para public 'CODE' use32
assume cs:UPX0
;org 401000h
assume es:nothing, ss:nothing, ds:UPX0, fs:nothing, gs:nothing
dd 0B4h dup(?)
dword_4012D0 dd 175Ah dup(?)
TlsIndex dd 23F2h dup(?)
UPX0 ends

; Section 2. (virtual address 00010000)
; Virtual size                  : 00004000 (  16384.)
; Section size in file          : 00003600 (  13824.)
; Offset to raw data for section: 00000200
; Flags E0000040: Data Executable Readable Writable
; Alignment     : default

; Segment type: Pure code
; Segment permissions: Read/Write/Execute
UPX1 segment para public 'CODE' use32
assume cs:UPX1
;org 410000h
assume es:nothing, ss:nothing, ds:UPX0, fs:nothing, gs:nothing
dd 8AF5D5B8h, 115E52Bh, 336D00h, 0AA1300h
dd 22600h
db 1Bh
byte_410015 db 0EEh, 0FEh, 0B7h
dd 1CEC83FFh, 2024448Bh, 3D01008Bh, 0C0000091h
dd 943D2E76h, 0D7840F06h, 0D6CDE466h, 74961105h
dd 91933D63h, 0FFEEFBBDh, 0C483C031h, 4C21Ch
dd 0D26B48Dh, 3D906600h, 79731B8Dh, 0FBBF053Dh
dd 7506DDB7h, 44AC732h, 2404C717h, 2E8060Bh
dd 831C2C00h, 0DB35B60Fh, 0EF3B01F8h, 18C04A85h
dd 3B8D0FFh, 0FFBB6DF2h, 3FB2EB00h, 4A8381Dh
dd 213277B2h, 381887D2h, 0EDF6D80Ch, 2D001FE9h
dd 9083748Dh, 5CF60838h, 577480F7h, 2A4EB185h
dd 1DF23818h, 753342C2h, 4B0118CCh, 6F42CAD9h
dd 17090B22h, 1100A4F6h, 0B0165ACh, 1D94C918h
dd 5F041BC8h, 5A4160F8h
push    es
push    ebp
mov     ebp, esp
push    ebx
mov     ds:52A8A114h, eax
leave
idiv    dword ptr [ecx+1C074087h]
cmp     [edi+0], esi
inc     ecx
add     cl, [ebp+0D8B6FDh]
fisub   word ptr [esp+ecx]
or      edx, [eax]
inc     eax
dec     ebp
in      al, 0B1h        ; Interrupt Controller #2, 8259A
mov     dh, 7Dh
mov     bh, 0Eh
add     al, 7
or      [ecx+8], ecx
inc     eax
adc     [ecx-402063E8h], ecx
fbstp   tbyte ptr [edi+4]
add     eax, 7020A1DCh
dec     edx
jnz     short loc_41015A
daa
mov     ah, 8Bh
adc     eax, 6B10200Ch
mov     edi, 0F0C77DDh
pushf
and     esp, 0FFFFFFF0h
pop     es
or      ch, ah
sbb     [ebx+ecx*4-278194EBh], edi
cmp     esi, [edi+82D00A1h]
add     al, 0A1h
add     al, 70h
dec     eax
add     al, 0B4h
mov     ebx, eax
jnp     short near ptr loc_410113+4
dd 0AC22FEFFh, 2D0E1C89h, 0B41D8B44h, 49A31C81h
dd 3D8B392Ah, 10438BFBh, 6C8C2C28h
adc     esi, [eax]

loc_41015A:
fnstenv byte ptr [eax]
add     fs:[eax+60h], dl
add     edi, esi
or      al, 0F6h
mov     dh, 0DBh
mov     bh, 3Ch
lea     ebx, [edx]
sub     al, 0DEh
jns     short loc_41017E
int     3               ; Trap to Debugger
wait
jnb     short near ptr loc_41011E+2
push    edi
fild    dword ptr [eax-38FE1FE2h]
jecxz   short near ptr loc_4101F4+2
pop     ebp
div     edx

loc_41017E:
sbb     cl, [edx+ebp]
sub     [ebp-11663BBDh], ah
shl     eax, cl
js      short loc_4101C7
retn
db 90h
db 0CFh, 12h, 1
dd 0BE94A015h, 197610D8h, 5F529C01h, 0E661021Fh
dd 25154236h, 921B10CCh, 0F76DD35h, 8F0090BCh
dd 8E605356h, 106B0B3Ch, 0ED0C2D50h, 9AD6084Eh
dd 0EC1B1275h
db 14h, 0A3h, 6Ch

loc_4101C7:
outsd
daa
mov     esp, 13C9B1CFh
push    ss
sub     eax, [edi+edx]
or      [ecx-7F11883Ah], cl
jl      short near ptr loc_4101EB+3
sub     [ebx-7AE61E00h], esp
div     byte ptr [esi+esi*2-69h]
arpl    [edi+70081B11h], di
icebp

loc_4101EB:
mov     eax, 6AD6FF60h
loopne  loc_410205
jnp     short near ptr loc_4101C9+4

loc_4101F4:
fild    word ptr [esi+3]
db      65h
lock clc
pop     ebx
pop     esi
pop     ebp
retn
dw 0C79Fh
add     eax, 7E30B73Ah

loc_410205:
fild    word ptr [eax]
mov     esi, 3EBDEB04h
scasd
cmp     eax, 57B77BACh
sbb     [ecx+5409A324h], ah
shl     byte ptr [ecx-117B08BEh], 1
wait
adc     [ebx], ecx
sub     dword ptr ds:3EC9AF24h, 0B3F7B64Ch
das
and     bh, al
inc     ebp
loopne  loc_41026E
push    es
in      al, 76h         ; CMOS Memory/RTC Index Register (Extended RAM)
jbe     short near ptr loc_4101E4+4
cmp     eax, 0EC0D27F4h
lock push es
cld
loc_41023E jo      short near ptr loc_41023E+1
outsd
cld
aas
mov     edx, gs:[ebp-4]
mov     eax, [ebp+8]
add     eax, edx
movzx   eax, byte ptr [ecx-42h]
ror     byte ptr [ecx+7D83F845h], 0F8h
pusha
jle     short near ptr loc_410270+4
db      65h
sti
mov     ebx, 7F7A0577h
adc     al, 8Bh
push    cs
rol     byte ptr [edx], 89h
ror     dword ptr [ebp-3DB1FABh], 73h

loc_41026E:
jg      short locret_4102E7

loc_410270:
test    dword ptr [eax+1930EB08h], 51B7E2Fh
cmp     [edi+15h], edi
sub     dword ptr [ebp-8], 5
and     esp, [eax]
wait
sbb     esi, [edx-7CEFF0F7h]
push    es
sub     eax, 0B6DB5EFCh
not     byte ptr [ebx]
jle     short near ptr loc_410221+8
lea     edx, [esi-0BE90BA1h]
test    eax, 0B18869A7h
xor     eax, 0B060AAADh
lea     eax, [eax+3]
sar     byte ptr ds:6C0B3C2Ch, cl
mov     ds:0C747BA41h, eax
inc     esp
sub     ebp, [esi]
jnz     short loc_4102CB
mov     dh, 0F7h
test    [ecx], ebx
xchg    eax, ecx
sub     al, 82h
db 0C5h
clc
xor     dh, [esi+18h]
xor     [ebx-46B796DBh], dh
setalc

loc_4102CB:
dec     eax
jz      short loc_410300
or      byte ptr [eax+ecx*2], 0D5h
sbb     [ecx], ebx
mov     es, eax
ficomp  word ptr [edi]
mov     byte ptr [esp+eax+19h], 0
adc     [ecx-15h], bl
retn
align 2
ror     dword ptr [edi+4], cl
or      al, 89h

locret_4102E7:
retn    14DEh
dw 2063h
dd 89D88EBFh, 755F4214h, 7B510041h, 145D8778h
dd 0C715B817h

loc_410300:
add     [edi], di
std
icebp
xor     bh, cl
push    edi
mov     al, 4Ch
test    byte ptr ds:0E750246h, 0A1h
pop     ebp
xchg    eax, esi
sbb     eax, 0F48C0247h
pop     edi
pop     ebp
sub     bl, bh
lodsd
push    ss
dw 0FDDBh
dd 0BC65891Ch, 0ADC789ABh, 0D263297Ah, 0E8C1FAFFh
dd 40E0C104h, 0D2317C11h, 0C81C429h, 3D2B67E9h
dd 0A915C8Dh, 440025D0h, 0CEB52C86h, 0EC45DB6h
dd 45F6C0C8h, 6F8DFE38h, 0C783D800h, 0FF770801h
dd 7589F389h, 986FD0D4h, 4B211BFEh, 5DF980DEh
dd 9583870Fh, 24FFC924h, 0E9242E05h, 6251308Dh
dd 0A827D0D8h, 0A660F60Eh, 8336907Ah, 753901C2h
dd 6CDEC7C6h, 0D285DF3Bh, 0C201891Dh, 0C02FB68Dh
dd 0FDD68101h, 0FF40C6FFh, 75D0395Ch, 0C45539F5h
dd 54FC820Fh, 0F3ED7F8Bh, 85B63AF6h, 0A3DC0AF1h
dd 0A3E00727h, 86CF6800h, 3FEAD9B5h, 0DF98728Dh
dd 0E81427EBh, 4775200Ch, 336329BEh, 30DFB01Fh
dd 548DCCC9h, 89620110h, 0ABD189F0h, 84A5FFF0h
dd 2C60624h, 14A8D7Fh, 8801418Dh, 0FDAB0F19h
dd 6B486D6h, 4F165F4Fh, 758BCC4Dh, 0BFEDF6D0h
dd 950FAFBDh, 7FD4CDC1h, 940FCE89h, 4DE8D445h
dd 59CE09D4h, 0E17496CFh, 0EBD4AA75h, 1079AFB8h
dd 6E6B0E74h, 0D15879B7h, 1B5DAF9h, 0B3C871C1h
dd 0F50D4BDh, 0E283A622h, 0D8701B01h, 723BB433h
dd 732701C6h, 0E77AA962h, 39B391B0h, 0C13A906Dh
dd 0F73F7B7h, 3E171B4Ah, 97081285h, 0FBE18922h
dd 3EC8B0BEh, 0F010348Dh, 4F765D26h, 265DBF5Dh
dd 0C44D8BF0h, 0A15B75C9h, 0ED83F094h, 38897B82h
dd 0C0A1340Eh, 8BD41409h, 0FEDBA1B5h, 74A2048Dh
dd 0C475393Bh, 0C80F4F72h, 2B1948D5h, 5558BC21h
dd 63BD0FD5h, 34DA1E30h, 94FED488h, 0BE1642BBh
dd 918C5A1h, 468DBF74h, 220C1E40h, 0D8D2D2F0h
dd 0D9CB06C6h, 3C6C1CDCh, 5C435D8Bh, 0CB836C1Ch
dd 6DFDCC8Eh, 2143340Ah, 7114897Ch, 90B1C0B6h
dd 83023FC3h, 0FCEF7C86h, 3CC4455Ch, 0F866CB6Fh
dd 22501E42h, 65C00C6h, 0A48C0A0Ah, 0AE273021h
dd 0EF3615F6h, 89070806h, 0CEC707C1h, 0FB0DB714h
dd 8C723832h, 9C1F2207h, 0F713589Ch, 356D836Dh
dd 9D0A2039h, 0D0319D0Ah, 1B170BA9h, 0E96E85BBh
dd 0A531534Dh, 5B6F97A2h, 0CDBDD7Bh, 120E5FB8h
dd 3748FF6h, 0F7367E83h, 0C5F66E6Fh, 0D057420h
dd 80111580h, 65C2F702h, 0BD6BE7Bh, 40A0Fh
dd 655D6D27h, 0D108A681h, 0FF028881h, 87D8FB0Fh
dd 8BE2AEB7h, 8114249Ch, 0C0DE06B4h, 0BE150013h
dd 0C7937C9h, 87208924h, 7E7B3315h, 81C94FBFh
dd 1E7527FBh, 10020061h, 0FB1E990Ah, 0F6200419h
dd 0A34091C1h, 0EF9C4124h, 80517DB7h, 76063DA7h
dd 0B980B525h, 36ED731h, 0D1A0579h, 8BB94037h
dd 92FBF849h, 5B320509h, 0A10FC3F3h, 3E2E590h
dd 25694347h, 0E7E16BA1h, 11798FA0h, 40A0508Dh
dd 1D12E8DDh, 1F0B156Fh, 0C30CBBE9h, 460C8574h
dd 0BABFC35Fh, 8EFFEC18h, 3D805E5Bh, 74FFFB92h
dd 74DB8521h, 9D14FF0Ch, 626C820Fh, 0F4A2EB63h
dd 0FB1A601Bh, 43DFC1ADh, 31C35B18h, 446EEBDBh
dd 148B0143h, 97832585h, 0F0ABC774h, 0A17FC9EBh
dd 4CF0F728h, 0F073ACCh, 9897103Fh, 0EB8BFBD4h
dd 0D0FAF94h, 0A3F603F8h, 1474DD08h, 0F3A61026h
dd 0ED9F000Ch, 8B38B1A9h, 34047154h, 6CD0B89h
dd 63088CF6h, 6C279C0Dh, 981FE67Eh, 83147B5Fh
dd 5870643Dh, 85A30A74h, 0C71D62Fh, 127AF82Eh
dd 0B15AEEACh, 14384BEDh, 0B83FA840h, 0F6ED9014h
dd 2D1FDBC6h, 0FEC17904h, 0E07E8502h, 7DEEA1D5h
dd 48B0F08h, 29A199Dh, 612EA3F3h, 3901C3BFh
dd 3DEC7FDEh, 0D85E2864h, 0A80DD3B0h, 2D28A408h
dd 9F4B30A1h, 0B270ABC9h, 0DC00E2F9h, 4C704414h
dd 0B70BC2EDh, 0E20A3C7Ch, 7F662D7Ah, 0A41B9AF0h
dd 12DCD603h, 0BA66229Fh, 7527D819h, 436AE80Ch
dd 0CC96AF04h, 8BF6EC96h, 752C085Bh, 0F42C45D5h
dd 0E6FA31A3h, 56C3777Ch, 40CFF631h, 92B96084h
dd 0D815103Bh, 0F7A53F17h, 0D70C7466h, 1EFC3CA9h
dd 0C3BAF60Eh, 52C841EEh, 894A0389h, 0D637D86Ch
dd 0A0A1A16Eh, 3522A689h, 433D8B59h, 7A5C7808h
dd 185BA4BEh, 608E7263h, 382D188Ch, 5C8B76BAh
dd 450F905Eh, 390F5B13h, 0A8F9610h, 0BA74D215h
dd 17FFFE97h, 0C339028Bh, 4EEB0A75h, 0D939088Bh
dd 8BF32974h, 0F13E0842h, 0CA5818ECh, 8B7F4DF4h
dd 60EC8748h, 354A326Ch, 0EB2D6C2Ch, 8F1E32D0h
dd 0CEA34575h, 6FDBEBD0h, 0A3B0878Fh, 547401F9h
dd 9759820h, 30AC733Dh, 6075186Ch, 7D981A9Fh
dd 8473B15h, 0D964DBD5h, 0E9E7BDF7h, 54CC0011h
dd 0DC2FC06Eh, 743B37B2h, 544F1E37h, 93D8B280h
dd 0C0C2BEDh, 0B2EB8F4Bh, 78F12210h, 0C1906C06h
dd 7A46B8FCh, 4F91D5E0h, 179F1EA1h, 916F1921h
dd 588DCE65h, 0C577A340h, 0B855F938h, 0AF6452ACh
dd 0B532776Fh, 671A0822h, 18F42B13h, 8CFE258Dh
dd 5755AF84h, 6256D789h, 0DE871353h, 14295677h
dd 2D471C56h, 91AE03CCh, 6669CC1Ch, 0AB9BC7A4h
dd 9FB90E9Dh, 22750404h, 0DF8181A5h, 0B6841040h
dd 0C88070Ch, 580BF303h, 72F6BAB8h, 7E1F36F2h
dd 0F173AF95h, 56E26C8Dh, 4D6C9E40h, 0EF20C20Dh
dd 0FED4B514h, 8CBD4A8Bh, 4C564CB5h, 881704D2h
dd 6CD6DAE1h, 0F24CB62Dh, 4AE6AF9h, 5BAF492h
dd 1030A947h, 61A3833Ch, 7944CAD8h, 32F70802h
dd 1CE4E13Ch, 5C0E0AC4h, 23935D7Fh, 5C5CAFD9h
dd 6D085526h, 99553C3Dh, 0E6552207h, 0C6B3F74Eh
dd 0B11A32Ch, 24818F0Fh, 0D0F9ECBBh, 2985EE26h
dd 1E044327h, 174F830Ah, 2423086Dh, 0F0CC367h
dd 5FFDBED0h, 8B4A7327h, 4738B13h, 8D084BD1h
dd 0DB0B17BAh, 86A535F9h, 0D4928B05h, 37E5110h
dd 0F60F42FEh, 295937F9h, 0B91003FAh, 6DCFBBAh
dd 1C063C9Ch, 0ACB3038Dh, 0B22FBB49h, 0DBB6723Dh
dd 27A87B2Ch, 0B9B318A1h, 61167237h, 71C3D0Bh
dd 0C4D8E512h, 20AA366Bh, 0F4404BBh, 0F5238CE0h
dd 8F9EFCFh, 4C894C74h, 35532C5Dh, 43841B77h
dd 26761016h, 0BF8DAEB7h, 89F805FDh, 0C2C981E9h
dd 0ED8566FFh, 290C0278h, 0B9CA01F9h, 3B097DBh
dd 0FF558B52h, 87D930CDh, 0F189FF77h, 679C984h
dd 0FF2FCE81h, 3CB9FE29h, 3529F201h, 7F5B108Bh
dd 6DE1C430h, 370AB761h, 0B64B8B30h, 308E513h
dd 0B00E1191h, 0F98119D8h, 2C5FD2F6h, 4F8F4349h
dd 4349EB5Eh, 0DD001E1Ah, 66FB1FF8h, 5051E25Ah
dd 0F1141059h, 8115720Ch, 2BD8FB28h, 838F21BCh
dd 1813D609h, 0C129EB77h, 20884C10h, 0D35958B5h
dd 7F2F1AFh, 800C1637h, 74FD421Fh, 2C74FC4Ch
dd 0D6896DF8h, 22085323h, 74FE0448h, 0CF20D928h
dd 285D0E8Dh, 70161C40h, 0E3057024h, 0FF12B621h
dd 0C3BF0CACh, 0C0FA6D44h, 0FE401472h, 9AAC150Fh
dd 0FEB9DAEBh, 1AAF92CDh, 0EBE3DB19h, 0B8DC1FC3h
dd 0EB0EF80Ch, 68CDFFA6h, 0C4B1D689h, 3C6A754Bh
dd 0DF8918ADh, 0CB492D95h, 0DA16B0F6h, 5D0AC10Eh
dd 26BB33CFh, 8128E153h, 1CC83EE1h, 0EEB200Dh
dd 17810FDAh, 2BFB894Fh, 0EF4B135Ch, 67EDF631h
dd 0D840E889h, 3601718Dh, 9D4A4AC6h, 0ACA9ED91h
dd 0B510DB8Fh, 0CC16562Fh, 0A35C08F2h, 93742ECCh
dd 1875DE3h, 3C89B3E3h, 0FB4F2A24h, 2BEB534Eh
dd 1C5D10FCh, 25168B0Dh, 29B0740Ch, 0D79985C3h
dd 37DB02B0h, 0E383EAF4h, 0FA80F920h, 461745Dh
dd 0ED60BD7Fh, 0C184C0B6h, 1514C56h, 7BB116B5h
dd 864ACC2Dh, 16857D12h, 0CD01A0DFh, 3EB79A4Bh
dd 488DD4EBh, 0B696DCD8h, 0DE501701h, 1AE83F3h
dd 0D976DABEh, 12A66D26h, 69448F50h, 88403CE8h
dd 16DCE874h, 611F6FCDh, 0F33EF7D6h, 0F189CFB3h
dd 0B1312DBFh, 0F7E15510h, 39FDFF08h, 0B08D0FDFh
dd 892C1E00h, 19EBC2EEh, 1977DB20h, 58312B06h
dd 39FE8933h, 75816FFBh, 915F35B1h, 0FD647E54h
dd 40F0E1CAh, 0ED0F49BAh, 0AFC629C6h, 2D0B7DCEh
dd 518BF3CDh, 9F9F02C4h, 83DB7B61h, 0DC4637E1h
dd 0F7CF6947h, 666DB61Fh, 235A0C2Bh, 1EC65156h
dd 1C9B5CD9h, 0FF165E4Ah, 4BF61EC9h, 5E00B673h
dd 0EBD889C6h, 0EF8957CCh, 0EC7396C0h, 36678EB7h
dd 0EF6C68B1h, 0A7EEB583h, 0B4AA15B9h, 1EF832Bh
dd 0E19847B5h, 0EDC3F887h, 0AC9EE775h, 0D200E4D5h
dd 0BC242C34h, 247909FEh, 9DFEAD07h, 70EA46FEh
dd 0A87D75D8h, 13AC5FD0h, 32F6C9C8h, 57E583CFh
dd 2DD26441h, 551CE3h, 0DB3B4557h, 0BE165B5Dh
dd 57598D09h, 764905C1h, 0BBEB7193h, 125FC1BFh
dd 925EF9E6h, 87146F63h, 0F19821D3h, 0AF307C08h
dd 3A8098C7h, 0D0B99C2Eh, 390021B0h, 127D614h
dd 0CEB5BF09h, 12F64795h, 0D11B5518h, 478DF589h
dd 6BAA7DB9h, 645C9B78h, 0DF083FF9h, 91A58300h
dd 2AA65BE5h, 3541F6E1h, 20ADB5B3h, 26A7839Ah
dd 0C9C25C21h, 1E38BA5Dh, 0F7304D84h, 84BB7118h
dd 0BACC0B57h, 0B67D9E36h, 48C4D49Bh, 291214C5h
dd 6833DAC5h, 7E74FAE1h, 63A8DA29h, 0BE29E37Dh
dd 77F0C3B5h, 0E752A3Ch, 36ECC31Fh, 3ADC1A0h
dd 0DAF6740Dh, 1C9AD8F9h, 14CFE818h, 0EA787139h
dd 15D88EC2h, 5C15480Dh, 36C58349h, 0EADBF6BDh
dd 0E843FF7Dh, 4C5BC249h, 0BE7FBD4Bh, 168EFFADh
dd 17F00C2h, 0E75F7421h, 0D6F6D220h, 0C7241234h
dd 0DD18FF85h, 6FB7333h, 6FC65A58h, 80908415h
dd 0DC84B23Eh, 0F037BE10h, 0DFE7EBC7h, 0DD29D589h
dd 0CD3FEE19h, 3C70B331h, 0DFD1992Eh, 7BC30100h
dd 0D72B6FBh, 0F424D23Eh, 25F8D6Fh, 0E737A161h
dd 986398DEh, 96EBDF67h, 0B5B83E6Fh, 61578F2Dh
dd 0D28602C7h, 0E7DDB175h, 0A3BB3538h, 0F93FDAF7h
dd 15D6DD02h, 7C6BB2Ah, 2F034903h, 1D1B968Dh
dd 0C0A7B85h, 3CFF2A51h, 365B0619h, 262E021Ah
dd 3818FB43h, 44686BDAh, 18184BDBh, 68B76F55h
dd 253283Bh, 0D2EB961Fh, 0BABFEB05h, 0A77EC990h
dd 0BA5CEE5Dh, 0F03F095Bh, 90E06F52h, 5EEC13Bh
dd 0F683D053h, 0B4778301h, 88B6FEDh, 2F74C6CCh
dd 6198C6F7h, 0A8C5D6D7h, 494977F9h, 0B8F08325h
dd 50ADAB42h, 5C1E3F04h, 7B18DA2Fh, 0F2B0773h
dd 752EC394h, 75ADC82Dh, 0DFD23877h, 327E01FBh
dd 74244A5Dh, 6685864h, 3CC0AF6Fh, 0ED6AB6A8h
dd 7880AF61h, 11673155h, 6FA936Fh, 0E2EBB872h
dd 3DFFB990h, 0D0C931C3h, 0D51B750Fh, 0A1C68F66h
dd 580C408Bh, 93AD56BCh, 0A2345C90h, 3E1BA276h
dd 846895Ch, 46C72150h, 0B7EA402Dh, 0E7EEEC1h
dd 0C401EB6Fh, 0F4750F98h, 65AE57C8h, 5685ED56h
dd 6FD0F403h, 5057A483h, 4222D389h, 2EDD0828h
dd 52044262h, 3E9D0885h, 0DBE60DD1h, 26563459h
dd 0AD0C5358h, 0A7A6FFABh, 101798Dh, 89FA01D1h
dd 5C883D7Bh, 9DB3DC01h, 5F105A90h, 42C8825Bh
dd 2F0B1787h, 0DE7AD6FBh, 5314C07Dh, 0AC18A705h
dd 0B104438Bh, 56E8BD0Dh, 892CE221h, 498118F2h
dd 6C0F460Dh, 218A8FFFh, 4C19363Dh, 1B9FD6EBh
dd 1F4FFBBFh, 0D055896Ch, 0E900E281h, 89CC4589h
dd 0E22EC84Dh, 11D6EBC5h, 650B7D11h, 0C525C7B8h
dd 50193C46h, 0B51B101Bh, 29E8E80Fh, 60C81C4h
dd 8A77DF7Ch, 4CDC8367h, 30BC2207h, 82D76D4Fh
dd 0A6DBBCC6h, 0CFC1713h, 0A1E192F6h, 2E9682D4h
dd 8B12740Dh, 0BF75B074h, 18F889EFh, 5D7156Ch
dd 0E32D7571h, 3BD91B77h, 0BC6D70E5h, 766F7C8Dh
dd 0F946F8EBh, 728D0278h, 9078601h, 9F0A0142h
dd 2FF68DDh, 8801C183h, 0AE1EFF41h, 2DADE375h
dd 0B36F8964h, 80DCB733h, 847001D4h, 83558D25h
dd 0CDC0F75Ah, 4D8B4C18h, 150FE6D4h, 0DA69EE8Bh
dd 4044DB44h, 3166A4Ch, 19085C6Fh, 30E763Ah
dd 7F58BF87h, 0B75DE55h, 0FA6F3FDh, 8486C097h
dd 0F60FF2A3h, 2310D045h, 0ADD9BDB5h, 9B45C678h
dd 38BC655Ch, 0FBEF857Dh, 2D6FE0B9h, 0D071078Bh
dd 94534DCCh, 0E1E6F08Bh, 0C04D8000h, 3B7F47EBh
dd 0B6C1D7E3h, 0C85D1D87h, 0A4E41D2Fh, 3B051C8Bh
dd 3607386Ch, 0B6BCD6FFh, 2B70082Ch, 0FC4714B5h
dd 0BD9E5429h, 4A8BE611h, 17DB7401h, 0D3B3C28h
dd 0C4CCDBADh, 6EC5A933h, 0B6D90DB4h, 4C0DAF09h
dd 1AB41E41h, 41D88CB4h, 4589B067h, 6BEE189Ch
dd 3C2A3B6Fh, 0EE0D54C3h, 186290C0h, 8306FFDCh
dd 7510087Bh, 0C738DDEh, 8D2C18B9h, 0EEBF42EDh
dd 4B4ECA75h, 0D9C1106h, 85028407h, 9521F2ACh
dd 4A2F5D8Bh, 6B48E9Bh, 78A45554h, 3360613Ch
dd 904FEBB8h, 18DAA00Fh, 19B25DD8h, 65128B74h
dd 9A1A9CA8h, 47DD256Eh, 0F2DE74A4h, 5E419659h
dd 434B8D03h, 93BAC24Bh, 0CB426591h, 0C6488B34h
dd 0F9C28BB5h, 77CFC5BEh, 41AD02F9h, 51EAD81h
dd 0FB575E8h, 0D6CFAF8h, 0B41C4068h, 27FE0855h
dd 7A3F025Ah, 1AEA6590h, 95F31FEEh, 0C6FA06BDh
dd 0B60F919Fh, 0E05ADB1Eh, 0C07D7C4Dh, 0FBED4E8Dh
dd 4B042297h, 7B68D074h, 4488A66Fh, 1DB1CCDBh
dd 0EA5ECC02h, 1221E1CEh, 3C42BFB7h, 7F07C60Fh
dd 0B114751Eh, 0B6F12C87h, 3F1CC7B9h, 6D688CCh
dd 435FA5DCh, 945A02C6h, 3C4FA9EBh, 2EBC2835h
dd 0F228429Eh, 20E963EBh, 727589F9h, 7C2CE0D8h
dd 7B7FB5B9h, 713C3E7Eh, 757D3C5Eh, 1C6D8347h
dd 0EF010F72h, 42F4CFC7h, 75200A02h, 0ED750EDFh
dd 8C125812h, 0EB7B4674h, 6D73B06Fh, 8E0D326Bh
dd 0FA89847Bh, 0DD0A231Ch, 0BF56DA0Dh, 0E9746F80h
dd 2C590333h, 85DBEE74h, 7A833C95h, 0B8218939h
dd 56A0C141h, 43033BAh, 343EAEC7h, 235E1A19h
dd 0BDBF12DAh, 0C801CC6Ah, 55881031h, 83B5399Bh
dd 0A6B1E239h, 3CFAE80Eh, 755C0839h, 92C72220h
dd 821F0FECh, 203C51Bh, 8D98339h, 0B03EA0BCh
dd 0DCD4A974h, 410942E4h, 0C5087472h, 7EDDFA0Dh
dd 0DA03AA85h, 0EB869B75h, 0C99C00Ah, 0FCC66F93h
dd 0A0D620EFh, 9CFA54DFh, 0CB08C194h, 2497EA75h
dd 0DA1E15A3h, 45CC3A88h, 0A5BFF701h, 0B86D8382h
dd 0AB9B1440h, 6E870CDCh, 0FFD07DD9h, 9B53BACCh
dd 0DCD1737Bh, 0C6009A7Eh, 747D0DF3h, 301B0478h
dd 332C6D52h, 0A309FA5Eh, 48289ADh, 76D07DF9h
dd 66EC52A1h, 1539042h, 0C960184Dh, 8029FB77h
dd 18756E7Bh, 17214CDFh, 585FE6E9h, 0D75D0106h
dd 80116C60h, 7B04EBEDh, 0FD7D08B9h, 0D9B321EFh
dd 0C35CE172h, 0EA83ADEBh, 0A183B901h, 7D857CADh
dd 0A999FD78h, 0BAB33AADh, 7020C66h, 0BAEB6E7Fh
dd 88027068h, 1034D38Ah, 1B87AE03h, 70036EC2h
dd 340FF21Dh, 9BF1C083h, 15087561h, 0BEEB7B42h
dd 0CD691988h, 0D8DB0F68h, 40C61F0Ch, 1661462Dh
dd 0FEFAE890h, 67443920h, 1A75B32h, 7E8808A0h
dd 0E7B15AA3h, 89BF2084h, 1CF83FAh, 182D0681h
dd 40C8DEE3h, 1A2D1B27h, 0B473FCE2h, 763A639Fh
dd 0A67BED0Fh, 3EEFDC85h, 1C1E0BC3h, 8B3DB322h
dd 0BD01EE8Fh, 0AD61BE26h, 0A4EB02DDh, 247E1E1Fh
dd 620603D7h, 0FF076B06h, 7D8B3CEBh, 80BC5FB0h
dd 1E6280CEh, 565DF219h, 5F731CF9h, 0B98C9D7Bh
dd 0AB4FB92h, 0FAF4DFB0h, 190DC25Ch, 32E91838h
dd 3A9796BFh, 60C1B803h, 10277053h, 41817CD2h
dd 8DF93AE6h, 1B96DA5Ch, 79CE85ACh, 5B0A415Bh
dd 1C18C830h, 0F41C3AF9h, 3563B818h, 74372245h
dd 4C36061Bh, 0E0818483h, 1B246C08h, 0AEFBB030h
dd 0EBEB120Fh, 0A04D6F00h, 47D74D91h, 44EF5C73h
db  55h ; U
db 0A8h, 7Eh, 0B0h
db  6Dh ; m
db 6Fh, 62h, 44h
db  1Ch
db 0Bh, 3Fh, 0A8h
db 0F4h ; פ
db 0A0h, 5Fh, 0B4h
db    0
db 0F0h, 87h, 7Bh
db  4Ch ; L
db 73h, 35h, 0FBh
db  88h ; ˆ
db 4, 1Ah, 4Fh
db  1Ah
db 3Eh, 2Ch, 4Fh
db  1Ah
db 5Ch, 1Bh, 53h
db  37h ; 7
db 3, 1Bh, 0EAh
db  5Bh ; [
db 84h, 65h, 6Bh
db  1Eh
db 0FBh, 0DBh, 0A7h
db 0C6h ; ֶ
db 0E8h, 7Dh, 0E0h
db 0EBh ; כ
db 0E8h, 0D1h, 0A8h
db  25h ; %
db 0DCh, 23h, 16h
db  58h ; X
db 14h, 0A1h, 0ADh
db  26h ; &
db 0B6h, 0A7h, 4Bh
db 0E8h ; ט
db 7Fh, 6, 0D1h
db  3Ah ; :
db 19h, 70h, 51h
db 0A0h ;  
db 17h, 19h, 2
db  18h
db 0B0h, 0FDh, 5Dh
db 0E2h ; ג
db 7Bh, 56h, 75h
db 0DCh
db 0C4h, 5Ch, 0EBh
db 0DAh
db 9Eh, 0A8h, 70h
db  27h ; '
db 5Bh, 0B1h, 1Bh
db 0A8h ; ¨
db 49h, 0Ch, 5Ch
db  8Bh ; ‹
db 0C4h, 2, 0FEh
db  6Ch ; l
db 2Ah, 84h, 0F5h
db  70h ; p
db 8, 0C7h, 40h
db    6
db 0ACh, 15h, 0B7h
db  53h ; S
db 14h, 0EAh, 7Eh
db  35h ; 5
db 51h, 7Dh, 30h
db  8Bh ; ‹
db 35h, 0DAh, 0F2h
db  27h ; '
db 0F4h, 0Eh, 43h
db  30h ; 0
db 0C5h, 6Eh, 41h
db    1
db 0D0h, 0A2h, 0B1h
db 0AAh ; ×
db 2Ch, 76h, 0A4h
db    7
db 0FAh, 7Eh, 89h
db    3
db 24h, 66h, 0ACh
db  9Dh
db 13h, 0Eh, 89h
db 0B9h ; ¹
db 8Eh, 0Ah, 69h
db  2Ch ; ,
db 1, 88h, 8Dh
db  2Eh ; .
db 9Fh, 0DAh, 56h
db  60h ; `
db 42h, 0B8h, 2Fh
db 0F4h ; פ
db 8, 0B2h, 7Fh
db  54h ; T
db 0E0h, 81h, 49h
db 0F7h ; ק
db 1Ch, 0Bh, 35h
db  81h
db 3Eh, 17h, 0AFh
db  81h
db 89h, 5Ah, 83h
db 0D0h ; ׀
db 8Dh, 3Dh, 0D4h
db  58h ; X
db 70h, 6Fh, 0C7h
db    6
db 0Eh, 0E8h, 50h
db  10h
db 0B0h, 8Eh, 0Eh
db 0FAh ; ת
db 78h, 0F3h, 43h
db 0C1h ; ֱ
db 47h, 17h, 0E7h
db 0C0h ; ְ
db 42h, 8Eh, 47h
db  12h
db 0E9h, 0AFh, 0Ch
db 0D8h ; ״
db 3Eh, 52h, 0Fh
db  99h ; ™
db 0C2h, 0CFh, 0E7h
db  10h
db 74h, 0E4h, 8Fh
db 0DCh
db 4Eh, 60h, 0B0h
db  15h
db 0E7h, 5, 1Ch
db  77h ; w
db 4Dh, 0DCh, 5Ch
db    0
db 0Ch, 2Fh, 0C6h
db 0B4h ; ´
db 5Ch, 0C2h, 90h
db  1Ch
db 0C6h, 25h, 1Fh
db  7Bh ; {
db 2 dup(7Bh), 1Fh
db 0FBh
db 0Fh, 66h, 34h
db 0F7h ; ק
db 8Bh, 22h, 2Eh
db  9Fh
db 81h, 0B1h, 2Dh
db  4Bh ; K
db 0B8h, 0E4h, 3Ch
db  41h ; A
db 74h, 0F2h, 16h
db 0E4h ; ה
db 96h, 64h, 57h
db  9Bh ; ›
db 24h, 7, 1Fh
db  21h ; !
db 0C5h, 0DCh, 43h
db  83h ; ƒ
db 75h, 35h, 10h
db  45h ; E
db 20h, 0CBh, 0Eh
db 0D1h ; ׁ
db 5Bh, 0E2h, 21h
db  39h ; 9
db 0A6h, 8Fh, 8Bh
db  7Eh ; ~
db 0E5h, 5Eh, 0F3h
db  35h ; 5
db 2Ah, 0FCh, 7Eh
db 0FFh
db 7Eh, 1Bh, 1
db 0DFh
db 0AFh, 8Bh, 46h
db    3
db 5Fh, 70h, 1Fh
db  24h ; $
db 1Eh, 0C4h, 0F8h
db  39h ; 9
db 0DFh, 75h, 0EBh
db  14h
db 65h, 0C1h, 3Bh
db  6Bh ; k
db 0DAh, 20h, 39h
db 0E9h ; י
db 15h, 8Fh, 23h
db  1Dh
db 14h, 84h, 3Fh
db  38h ; 8
align 2
dw 0D702h
db  86h ; †
db 3Dh, 27h, 24h
db  0Ah
db 0AFh, 0Dh, 23h
db 0E4h ; ה
db 0D8h, 12h, 0F2h
db  6Ch ; l
db 53h, 40h, 0B1h
db    8
db 42h, 80h, 10h
db  6Ch ; l
db 0DDh, 5Eh, 8
db  80h ; €
db 38h, 0DDh, 71h
db  5Fh ; _
db 60h, 0FBh, 0C9h
db 0D9h
db 6Eh, 2Ah, 0
db  2Bh ; +
db 0ECh, 8Dh, 70h
db  95h ; •
db 74h, 0DEh, 47h
db  93h ; “
db 85h, 9, 68h
db 0C9h ; ֹ
db 0A3h, 0Ch, 7Ah
db  6Fh ; o
db 98h, 2Bh, 0AFh
db  30h ; 0
db 18h, 2Ch, 83h
db  34h ; 4
db 61h, 8Eh, 0C3h
db  8Bh ; ‹
db 1Ch, 3Bh, 35h
db  76h ; v
db 4, 2 dup(78h)
db  31h ; 1
db 0ADh, 0F0h, 7Eh
db  65h ; e
db 0DCh, 73h, 0DFh
db  23h ; #
db 98h, 1Bh, 83h
db  6Eh ; n
db 0C8h, 2Dh, 54h
db 0C4h ; ִ
db 42h, 0, 0Ah
db  91h ; ‘
db 8Eh, 3Bh, 0B9h
db  47h ; G
db 87h, 91h, 0E0h
db  75h ; u
db 30h, 0F1h, 2Ch
db  4Bh ; K
db 5Bh, 0ADh, 0Eh
db  31h ; 1
db 80h, 2 dup(66h)
db  87h ; ‡
db 47h, 5Bh, 6Ch
db  86h ; †
db 5Dh, 0B9h, 76h
db  38h ; 8
db 0ACh, 0DBh, 0E0h
db 0B7h ; ·
db 38h, 36h, 0DDh
db 0B0h ; °
db 11h, 9, 2
db  9Fh
db  66h ; f
db  83h ; ƒ
db 0FFh
db  83h ; ƒ
db 0ECh, 1, 0E3h
db  23h ; #
db 4Bh, 57h, 9
db  5Ch ; \
db 0E2h, 0F8h, 3Ah
db  75h ; u
db 16h, 37h, 6Dh
db 0DBh
db 9Bh, 7Bh, 8Dh
db  49h ; I
db 4, 21h, 28h
db  78h ; x
db 4, 0EBh, 51h
db 0F8h ; ר
db 7, 3Fh, 6
db 0B4h ; ´
db 4Dh, 0ADh, 48h
db  2Fh ; /
db 49h, 11h, 8Bh
db  9Dh
db 0DFh, 0E0h, 8Eh
db  96h ; –
db 0E4h, 23h, 0Ch
db  18h
db 79h, 0C6h, 0EBh
db  1Bh
db 8Dh, 1Ah, 0B4h
db  43h ; C
db 4Fh, 0C1h, 43h
db 0D9h
db 0C9h, 0BBh, 0AEh
db  0Eh
db 6Eh, 33h, 51h
db    2
db 1, 66h, 31h
db  3Ch ; <
db 11h, 2Fh, 75h
db  16h
db 0C4h, 0C6h, 96h
db 0E6h ; ז
db 10h, 1Ah, 0Dh
db  0Eh
db 0DFh, 37h, 0F6h
db  99h ; ™
db 0Bh, 23h, 18h
db  2Fh ; /
db 74h, 0F4h, 1Eh
db 0EEh ; מ
db 41h, 6Eh, 3Bh
db 0E8h ; ט
db 3Ah, 34h, 7
db  53h ; S
db 0BBh, 0AFh, 39h
db  75h ; u
db 86h, 82h, 89h
db 0BBh ; »
db 5Fh, 2Bh, 0F7h
db  6Ah ; j
db 0AEh, 0B5h, 0AAh
db  74h ; t
db 0Bh, 74h, 0B9h
db  2Eh ; .
db  5Ah ; Z
db 0B5h ; µ
db 0D6h ; ײ
db  7Dh ; }
db 13h, 89h, 0F2h
db 0E4h ; ה
db 0E6h, 7, 0D1h
db  34h ; 4
db 2Ch, 0E4h, 12h
db  34h ; 4
db 0E0h, 0A7h, 78h
db 0EAh ; ך
db 0DCh, 4, 0B2h
db  7Ch ; |
db 0C6h, 17h, 42h
db 0E0h ; א
db 0CEh, 16h, 9
db 0C1h ; ֱ
db 2Bh, 0A8h, 0FAh
db  73h ; s
db 8Bh, 25h, 0DAh
db  2Dh ; -
db 0C5h, 0FEh, 39h
db  74h ; t
db 0E9h, 19h, 79h
db 0F0h ; נ
db 0C8h, 58h, 0FBh
db 0B7h ; ·
db 56h, 0FEh, 44h
db 0BDh ; ½
db 0E8h, 0E2h, 31h
jmp     dword ptr [esi-25h]
db 0DCh
db 0CDh ; ֽ
db 64h, 8Fh, 78h
db    2
db 55h, 1Dh, 30h
db 0AFh ; ¯
db 0FEh, 0DBh, 0C0h
db  5Ch ; \
db 70h, 5, 6Ah
db  85h ; …
db 31h, 2Fh, 0C1h
db 0EFh ; ן
db 6Ah, 9Fh, 91h
db 0A5h ; ¥
db 1, 2 dup(0F8h)
db 0C8h ; ָ
db 2Bh, 2Ah, 84h
db  77h ; w
db 0EEh, 0Dh, 8Dh
db  0Fh
db 8Eh, 10h, 20h
db  3Dh ; =
db 89h, 0CFh, 0EBh
db  1Ah
db 5Fh, 35h, 0B6h
db  2Bh ; +
db 94h, 5Bh, 2Fh
db  57h ; W
db 2, 47h, 1Bh
db  9Bh ; ›
db 0EBh, 0DAh, 6Ah
db 0EBh ; כ
db 0F1h, 66h, 0Fh
db  6Eh ; n
db 45h, 63h, 71h
db  46h ; F
db 0D8h, 6Ah, 0BFh
db 0FEh ; ‏
db 57h, 75h, 0DDh
db  1Fh
db 0F0h, 0F8h, 5Ah
db    6
db 43h, 0BAh, 12h
db  46h ; F
db 0D9h, 53h, 0EBh
db  80h ; €
db 0D2h, 0D6h, 0
db 0F7h ; ק
align 2
dw 3966h
db 0C7h ; ַ
db 89h, 0F9h, 18h
db  79h ; y
db 1Fh, 0E6h, 14h
db  66h ; f
db 0B6h, 0Ah, 26h
db 0F1h ; ס
db 75h, 8, 1Ch
db  0Ch
fcmovnu st, st(3)
and     eax, 31D8CA16h
imul    byte ptr [edi+31h]
and     ch, [esi]
xor     cl, 38h
sub     [ecx-28h], ebp
and     eax, 5BBAFDBDh
or      cl, 0C4h
dec     ecx
mov     byte ptr [esi+eax], 0CEh
and     al, 0FEh
mov     bl, 9Dh
xchg    esi, [ebx+0AB3F363h]
pavgw   mm5, mm7
db      66h
mov     dh, 0C2h
cmp     [edi], edx
or      ecx, ebx
lahf
push    eax
add     al, 9Ah
sti
push    ds
mov     ch, [ebp+36h]
retf
db 27h
db  15h
db 0C1h, 8Ah, 0F0h
db  71h ; q
db 9Ah, 0EDh, 0C0h
db 0E2h ; ג
db 3Ch, 0AFh, 0E0h
db  35h ; 5
db 70h, 0E3h, 0Fh
db  2Ch ; ,
db 0FAh, 46h, 31h
db  1Eh
db 7Fh, 4Fh, 89h
db 0D3h ; ׃
db 0AEh, 0C0h, 94h
db 0E1h ; ב
db 81h, 0ECh, 54h
db  39h ; 9
db 73h, 66h, 0E8h
db  34h ; 4
db 5, 4Dh, 7
db    4
db 58h, 34h, 0DBh
db  52h ; R
db 0A5h, 1Ah, 1
db  5Eh ; ^
db 0Ah, 33h, 0Ch
db 0BFh ; ¿
db 43h, 67h, 0A2h
db  39h ; 9
db 0B6h, 6, 8
db 0EBh ; כ
db 98h, 7, 0E9h
db  0Eh
db 1Dh, 34h, 2Ch
db 0F1h ; ס
db 66h, 3Dh, 4
db 0F4h ; פ
db 0D1h, 0C4h, 0C0h
db  98h ; ˜
db 4, 6Fh, 9Bh
db 0A8h ; ¨
db 0EBh, 3Ch, 88h
db    1
db 0D3h, 0E0h, 0A7h
db  24h ; $
db 58h, 37h, 10h
db  77h ; w
db 14h, 0A2h, 0D3h
db 0BBh ; »
db 1, 8Bh, 81h
db 0C4h ; ִ
db 5Ah, 9Ah, 5
db 0CCh
db 6Dh, 41h, 6Fh
db  13h
db 18h, 6, 17h
db  52h ; R
db 91h, 82h, 47h
db 0F2h ; ע
db 0E4h, 0F0h, 0CCh
db  3Dh ; =
db 56h, 0FAh, 18h
db  83h ; ƒ
db 0FBh, 3, 0FCh
db  0Bh
db 81h, 38h, 0Bh
db  22h ; "
db 0Ch, 5, 62h
db  0Bh
db 1Ch, 83h, 38h
db  92h ; ’
db 0B3h, 9, 0F3h
db 0E4h ; ה
db 19h, 0ECh, 81h
db  16h
db 8Ch, 0A6h, 0Ch
db    2
db 99h, 0B6h, 0B0h
db 0EAh ; ך
db 19h, 14h, 8Ch
db  2Fh ; /
db 0DFh, 0B2h, 0AEh
db 0C8h ; ָ
db 10h, 2Ch, 0CFh
db  5Fh ; _
db 0DEh, 0B0h, 17h
db  92h ; ’
db 21h, 15h, 75h
db 0DFh
db 0B2h, 80h, 0BDh
db 0A5h ; ¥
db 30h, 12h, 74h
db 0D2h ; ׂ
db 0B2h, 38h, 59h
db  60h ; `
db 18h, 0B1h, 0DFh
db  7Dh ; }
db 81h, 0EEh, 3
db 0F7h ; ק
db 47h, 0C9h, 84h
db  24h ; $
db 40h, 6, 0F8h
db 0B7h ; ·
db 7, 8Ah, 0D7h
db  22h ; "
db 3, 4Dh, 2Fh
db 0C7h ; ַ
db 9Fh, 93h, 0Dh
db 0D5h ; ױ
db 1Ch, 0A4h, 4
db    1
db 34h, 9Ch, 80h
db 0DFh
db 0E0h, 4Dh, 0B5h
db  7Ch ; |
db 17h, 0ACh, 74h
db  4Dh ; M
db 8Bh, 0Ah, 63h
db    4
db 8Dh, 81h, 0FFh
db 0DCh
db 76h, 0F3h, 0B7h
db 0FEh ; ‏
align 2
dw 0D1F7h
db  21h ; !
db 0C8h, 25h, 80h
db  74h ; t
db 0EAh, 0A9h, 4
db    0
db 41h, 5Dh, 80h
mov     edi, 6C59F0h
retn
dw 0DA83h
db    3
db 29h, 18h, 4Ch
db  14h
db 6Fh, 0B4h, 8Dh
db  6Fh ; o
db 78h, 4, 16h
db  80h ; €
db 0F9h, 66h, 40h
db    4
db 0E8h, 3Bh, 0B9h
db  5Ch ; \
db 7Bh, 7Ch, 81h
db  59h ; Y
db 16h, 25h, 16h
db    1
db 0EBh, 2Dh, 3Fh
db  4Ch ; L
db 17h, 62h, 0F2h
db  20h
db 0CFh, 0, 2Ah
db 0D8h ; ״
db 3, 99h, 68h
db  8Bh ; ‹
db 0D1h, 0BAh, 2Ah
db 0ECh ; ל
db 3Ch, 10h, 0DFh
db 0E0h ; א
db 81h, 3Ch, 0B2h
db  33h ; 3
db 82h, 0D2h, 21h
db 0D0h ; ׀
db 75h, 6, 4Bh
db  6Ch ; l
db 45h, 5Bh, 7Bh
db  10h
db 1Dh, 8, 0
db  66h ; f
db 0DBh, 0DEh, 25h
db 0C4h ; ִ
db 6Fh, 82h, 0F3h
db  8Dh
db 83h, 1Ch, 1
db  21h ; !
db 0C5h, 0EEh, 0DCh
db  0Bh
db 60h, 2, 22h
db 0B0h ; °
db 8Dh, 80h, 18h
db  1Ah
db 0B6h, 56h, 7Fh
db 0A1h ; ¡
db 0FCh, 72h, 4Eh
db  8Bh ; ‹
db 54h, 0Ch, 18h
db 0F4h ; פ
db 35h, 0C7h, 0BDh
db 0FBh
db 25h, 16h, 0BDh
db    8
db 0A0h, 0D9h, 0F3h
db 0A5h ; ¥
db 89h, 0EAh, 2Fh
db  26h ; &
db 0ACh, 89h, 85h
db  78h ; x
db 0A7h, 46h, 3Ah
db 0F3h ; ף
db 3Eh, 0A5h, 6Fh
db  0Dh
db 3Bh, 37h, 3Ah
mov     ah, 0F6h
inc     edi
xor     eax, 62CE1485h
lock sub al, 1Ch
inc     ebp
add     al, 6Fh
sub     al, 0E8h
and     ah, cl
setalc
mov     bh, 0Eh
lahf
mov     edi, 108816FAh
test    byte ptr [esi], 74h
mov     ch, 0DFh
sub     byte ptr [bp+5475h], 0Eh
or      [eax-2], ebx
aas
sahf
popf
pusha
push    ebx
stosd
retn
and     eax, 0C25FED28h
adc     [edx], esp
xchg    eax, edi
push    fs
retn
db 31h
db 0EDh ; ם
db 0C5h, 30h, 66h
db  24h ; $
db 6Ch, 55h, 6Fh
db  89h ; ‰
db 8Fh, 64h, 86h
db  67h ; g
db 0Ch, 8Ah, 3Fh
db  2Fh ; /
db 0B5h, 8Bh, 0D5h
db  5Ah ; Z
db 77h, 46h, 29h
db  93h ; “
db 89h, 20h, 0Fh
db  1Fh
db 0Eh, 1Eh, 53h
db  12h
db 10h, 9Fh, 8
db  63h ; c
db 0A5h, 20h, 0C2h
db  3Bh ; ;
db 98h, 34h, 8Bh
db 90h
db 14h, 0ADh, 2Ah
db  7Ah ; z
db 5Bh, 86h, 0DEh
db  89h ; ‰
db 88h, 0Ah, 53h
db  4Ch ; L
db 80h, 0E4h, 0E2h
db  3Bh ; ;
db 0D8h, 35h, 78h
db  41h ; A
db 27h, 8Ch, 98h
db  19h
db 0C0h, 0F7h, 0D0h
db  21h ; !
db 59h, 23h, 6Eh
db  14h
db 0D6h, 0CCh, 0D8h
db  5Bh ; [
db 0BFh, 6Fh, 0E0h
db    4
db 3Ch, 2 dup(0DBh)
db  81h
db 9, 0E8h, 0EFh
db  31h ; 1
db 0E1h, 8Dh, 7
db 8Ah, 0DBh
dw 8B36h
db  83h ; ƒ
db 10h, 6Bh, 18h
db 0D6h ; ײ
db 48h, 13h, 65h
db  3Ch ; <
db 0Fh, 0ACh, 5Fh
db 0B0h ; °
db 13h, 0D0h, 0FCh
db 0EFh ; ן
db 0BFh, 3Dh, 0B8h
db 0B0h ; °
db 84h, 3Ch, 0
db 0DFh
db 0E9h, 4Fh, 2
db  76h ; v
align 2
dw 1519h
db  75h ; u
db 10h, 40h, 1Ah
db  86h ; †
db 2Dh, 0C4h, 50h
db 0E0h ; א
db 18h, 2 dup(0AFh)
db  83h ; ƒ
db 0CDh, 86h, 0F0h
db  41h ; A
db 74h, 0E3h, 0C7h
db  83h ; ƒ
db 9Fh, 26h, 9Ch
db    7
db 0D9h, 82h, 0FFh
db 0FEh ; ‏
db 0Ch, 0Ah, 8Bh
db  80h ; €
db 4, 0A6h, 0CCh
db    5
db 0C9h, 94h, 0EAh
db 0DFh
db 0E6h, 0A0h, 3
db 90h
db 0Fh, 24h, 94h
db 0EFh ; ן
db 6, 9Eh, 3Dh
db 0F6h ; צ
db 78h, 4Fh, 0CFh
db  2Ah ; *
db 0DCh, 0E6h, 37h
db  83h ; ƒ
db 0BBh, 6Eh, 0C2h
db  1Bh
db 0F6h, 12h, 76h
db  1Bh
db 0EBh, 2Ch, 5Fh
db 0B3h ; ³
db 3Eh, 53h, 0ACh
db  91h ; ‘
db 4Bh, 65h, 0F8h
db  87h ; ‡
db 0F2h, 8, 8Fh
db 0F8h ; ר
db 58h, 89h, 8
db  39h ; 9
db 0F0h, 7Ch, 0DCh
db 0DEh
db 0CFh, 4, 60h
db  76h ; v
pop     eax
mov     ebp, 0AF908F16h
les     ebp, [edi]
jmp     dword ptr ds:7088218h
db 14h
db  41h ; A
db 6, 19h, 64h
db  10h
db 0Ch, 8, 9Ch
db  1Ch
db 64h, 90h
db 4
db    0
db 0FCh, 81h, 0F8h
db  32h ; 2
db 0C8h, 20h, 83h
db 0F4h ; פ
db 0F0h, 0ECh, 0C8h
db  20h
db 83h, 0Ch, 0E8h
db 0E4h ; ה
db 0E0h, 20h, 83h
db  0Ch
db 32h, 0DCh, 0D8h
db 0D4h ; װ
db 83h, 0Ch, 32h
db 0C8h ; ָ
db 0D0h, 0C8h, 0C4h
db 0B8h ; ¸
db 0Ch, 32h, 0C8h
db  20h
db 0B0h, 0A8h, 0A4h
db  32h ; 2
db 0C8h, 20h, 83h
db  9Ch
db 98h, 90h, 0C8h
db  20h
db 83h, 0Ch, 7Ch
db  78h ; x
db 74h, 20h, 83h
db  0Ch
db 32h, 70h, 6Ch
db  68h ; h
db 83h, 0Ch, 32h
db 0C8h ; ָ
db 64h, 60h, 5Ch
db  58h ; X
db 0Ch, 32h, 0C8h
db  20h
db 54h, 50h, 4Ch
db  32h ; 2
db 0C8h, 20h, 83h
db  48h ; H
db 44h, 40h, 0C8h
db  20h
db 83h, 0Ch, 3Ch
db  38h ; 8
db 88h, 81h, 0B0h
db  29h ; )
db 32h, 84h, 43h
db    3
db 2Ch, 8Fh, 0CDh
db 0D7h ; ׳
db 8, 0BAh, 0
db  70h ; p
db 0A7h, 0, 0FFh
db    0
db 1Dh, 3, 54h
db  20h
db 2, 7Bh, 0FDh
db    2
db 0A3h, 0B1h, 3Ch
db  40h ; @
align 2
dw 878Bh
db  40h ; @
db 5, 96h, 0A2h
db  15h
db 0A7h, 0AAh, 22h
db  24h ; $
db 6Ch, 69h, 0FFh
db 0FFh
db 2 dup(0FFh), 62h
aGccSDw21Dll db 'gcc_s_dw2-1.dll',0
db  5Fh ; _
db 5Fh, 72h, 65h
db  67h ; g
db 69h, 73h, 74h
db  65h ; e
db 72h, 5Fh, 66h
db  72h ; r
db 61h, 6Dh, 0DDh
db    0
db 0DBh, 0FCh, 65h
db  5Fh ; _
db 69h, 6Eh, 66h
db  6Fh ; o
db 64h, 65h, 17h
db    0
db 48h, 0DAh, 0FFh
db 0FFh
db 0B7h, 65h, 35h
db  6Fh ; o
db 2Ch, 20h, 79h
db  6Fh ; o
db 75h, 20h, 68h
db  61h ; a
db 76h, 65h, 20h
db  61h ; a
db 20h, 70h, 61h
db  63h ; c
db 6Bh, 61h, 67h
db 9, 0EDh
dw 0DFB7h
db 0DEh
db 21h, 20h, 74h
db  68h ; h
db 6, 6Dh, 61h
db  69h ; i
db 6Ch, 21h, 27h
db  50h ; P
db 6Ch, 65h, 61h
db  73h ; s
db 0Dh, 0EDh, 0B6h
db 0F6h ; צ
db 0DCh, 65h, 6Eh
db  42h ; B
db 2Dh, 4, 52h
db  74h ; t
db 1Ah, 73h, 2Ch
db  7Bh ; {
db 6Fh, 9Bh, 0DBh
db  28h ; (
db 6Fh, 72h, 5Fh
db  2Dh ; -
db 6Fh, 2, 61h
db  6Bh ; k
db 65h, 35h, 44h
db 0FEh ; ‏
db 0DDh, 65h, 0Fh
db    0
aENv db 'E/nv : ',0
aS db '%s',0
db  59h ; Y
db 0Eh, 0B6h, 0B5h
db 0E6h ; ז
db 6Dh, 8Fh, 22h
db  28h ; (
db 64h, 63h, 78h
db  20h
db 0DEh, 6, 0B6h
db 0DDh
db 5Fh, 6Eh, 67h
db  0Bh
db 21h, 31h, 44h
db  73h ; s
db 73h, 77h, 0DFh
db  61h ; a
db 6Dh, 0E7h, 5Bh
db  34h ; 4
db 6Eh, 39h, 6Bh
db    3
db 5Fh, 4, 6Bh
db  5Bh ; [
db 6Ch, 0C8h, 0DDh
db  39h ; 9
db 6Ch, 2Ah, 6Ah
db  6Fh ; o
db 79h, 6Fh, 3Eh
db  54h ; T
db 0DBh, 0FFh, 7Fh
db 0F7h ; ק
db 48h, 49h, 53h
db  20h
db 2, 4Eh, 4Fh
aTYourPackage db 'T YOUR PACKAGE!',0
dd 21B01B00h, 4017B3FBh, 7003F200h, 0C007400Bh
dd 3216556h, 6007974Bh, 16F0738Bh, 0B2B61680h
dd 7EF2445h, 1796170Bh, 0BA4D1B60h, 75F47767h
dd 0B1D1C17h, 660669DDh, 3A65B539h, 0FFF85B11h
dd 2020000Ah, 74726956h, 516C6175h, 1879F675h
dd 0C342DB8Dh, 25D29B14h, 0B796206h, 8DB768D6h
dd 2749273h, 0C2D6464h, 0B78D8D13h, 33B370C7h
dd 746B6E55h, 86DBA077h, 92708DE3h, 4B6F6475h
dd 692663C3h, 0BBB7DB7Bh, 6F72116Fh, 6C6F0B74h
dd 734E7620h, 0ED6E4610h, 0A2E7650h, 61696233h
dd 0EF657A2Bh, 2E43EDA6h, 621B6700h, 6D2D3051h
dd 74FC6FB6h, 6F3233C0h, 4343472Eh, 4E47288Eh
dd 0FDAC8B77h, 38202955h, 1321322Eh, 2E5747F5h
dd 6EEB1D92h, 0F2067CCh, 352D1C2Dh, 99360525h
dd 80134BCCh, 145582C0h, 0AD94553h, 0FE591413h
dd 7A0120FFh, 7C010052h, 0C1B0108h, 1880404h
dd 0F82BBF18h, 0E0031CAEh, 92FFFFAFh, 200E43F8h
dd 7F0E0A71h, 4ECE6CBh, 381B0B4Ch, 4FECB164h
dd 0E4080E41h, 85FF3DF6h, 50D4202h, 54038344h
dd 3F37B21Fh, 0EE9A6900h, 367B4076h, 6C171000h
dd 64331560h, 13203BEFh, 94131780h, 4D60BE69h
dd 139B0678h, 1C8374A8h, 28B70161h, 81FFFD58h
dd 9BA12B75h, 83038645h, 0A7B0204h, 41C641C3h
dd 1BA690C5h, 0B4B2CDBh, 0DC2B4827h, 0D857202Eh
dd 63206A3Bh, 207B171Ch, 0A837D4DDh, 1F38A402h
dd 0CD97203Dh, 1EB35C3Ch, 11A0301h, 0EC239076h
dd 4C3C5720h, 0FD8D37B4h, 366E407h, 86038746h
dd 52058304h, 1C24C7BCh, 42BE8FB0h, 0EE6020Bh
dd 79130B47h, 240C83B6h, 78FB764h, 0F7FD855Dh
dd 202837Fh, 0C050C48h, 3F020385h, 0C35F0208h
dd 167F970Eh, 3414320Eh, 4E31D3B8h, 265C100Eh
dd 2035EF74h, 4617E713h, 0DB6EC207h, 6AC457E0h
dd 5041080Ah, 43BB0B41h, 58374D19h, 731C8823h
dd 0CB939B1Ch, 0B87C0093h, 48550043h, 0B083740Bh
dd 6D60B9h, 6FAC5744h, 6E35D29Ah, 0EBF8683h
dd 6429760Ch, 0F74BD84Dh, 78C3460Ch, 740B43C6h
dd 0CD965F0Dh, 360C96E7h, 0B9048493h, 1906E903h
dd 73E8384Ah, 0F6CAF660h, 1C0E4C29h, 0F4500549h
dd 0C86F7D05h, 41694336h, 0E90CFBAFh, 67D64C86h
dd 0A1433B82h, 0B6596643h, 730B4907h, 454F4E43h
dd 0B2C331BAh, 0F342440Ah, 995447A0h, 9B6840EDh
dd 8425067h, 0CCECD98Eh, 8267883Eh, 34D0E115h
dd 0F5AB1DDh, 0E03F3000h, 91BBB1B4h, 635783B7h
dd 0B4A200Ah, 450B5F69h, 0F784A90Bh, 42055EBAh
dd 59A33248h, 28C2C948h, 0A34A0FBAh, 581BA664h
dd 1BBA5807h, 6B7D871Fh, 0C5108D6Ch, 0E3C81404h
dd 440E5850h, 0BB6699B3h, 0E96D500Ah, 0C7F11014h
dd 63AB5C35h, 64CA0EC5h, 5FF81B32h, 68D9587h
dd 63142243h, 0B34933A4h, 0DA67D77Bh, 4E416A01h
dd 41CEBB60h, 3F8B027Bh, 1C9F202h, 0F16CAC3h
dd 85905B0Fh, 43BC8017h, 2C0A6E77h, 8B62928Fh
dd 29BCCCCFh, 9364C9FBh, 5043A343h, 8D011B03h
dd 77C365h, 5CE30B46h, 69BFBC4Bh, 0FC95B26h
dd 4392E302h, 2BB06C06h, 0E3431643h, 69B2C943h
dd 0B4C33068h, 658EC174h, 4633F493h, 340A4502h
dd 9A320A76h, 0E8E7A4EEh, 0CB4FD033h, 992DC9A4h
dd 46037878h, 0F739EF9h, 373B0120h, 6C87C3CBh
dd 86E78D0Dh, 40467783h, 45B2103Dh, 410CD336h
dd 0ED4610C7h, 0B35A79A1h, 0C2E76828h, 0B4D2587Fh
dd 6F314990h, 6BA69B02h, 942B3C37h, 47087824h
dd 57C096EEh, 3A041103h, 1C7036Dh, 0CB5D74D9h
dd 3F2C6D0Fh, 84CA64D4h, 0D7725615h, 423E2A00h
dd 0EECB96h, 204E340h, 9657CB14h, 41E70D74h
dd 41E24F20h, 0EB0B1847h, 43106F64h, 0DDB0062Ch
dd 0E55B1820h, 0C8B48B03h, 0B742D211h, 642FD640h
dd 0D3CEC039h, 2E00E48h, 41C12DC2h, 0E04CD8C3h
dd 374DC914h, 4D893421h, 60434CD7h, 4819015Ch
dd 47A2CF96h, 921B2D23h, 0C30C5B48h, 0D4F200B0h
dd 0F1BC4F74h, 0C0BB41C3h, 0C0968DF8h, 1530302h
dd 0F1164FE1h, 0B52B7434h, 0D108BF20h, 9607C98Fh
dd 76102FABh, 69A040D0h, 2C2328BAh, 0B0534290h
dd 56E0460Ch, 5CC15100h, 839DD349h, 58B42B58h
dd 6774D352h, 18086593h, 0BAE4882Fh, 27567731h
dd 4C50102Bh, 71A41B34h, 0F869A04Ah, 52023F71h
dd 96EB2C19h, 0C4EC8C8h, 20E5A9A3h, 0D3A41007h
dd 5950B105h, 802728AAh, 2B101908h, 542F2579h
dd 59860485h, 6C92B64Eh, 38822003h, 0A69A69A6h
dd 7C6A5E50h, 69A69A8Ch, 0BCAC9A9Ah, 36FEE2D0h
dd 166CB34Dh, 52442683h, 66B8364h, 744BCEE9h
dd 9A8A7E0Bh, 9A69A603h, 0C8BAAAA6h, 0B34DE4DAh
dd 0FAEE9A6Ch, 1A0E8406h, 0D34D3424h, 423A2E34h
dd 34D3564Ch, 665ED34Dh, 4D867A70h, 904D34D3h
dd 0B4ACA29Ah, 0D34D34C0h, 0DED4CA34h, 8B61F2E8h
dd 84FEDB28h, 392A03E7h, 90805113h, 0B64774h
dd 21141714h, 28EC00ADh, 80E30380h, 0EC511232h
dd 8040035Ah, 9503105Bh, 192482ADh, 10FCD903h
dd 40A00104h, 70381C00h, 70580041h, 0E079004h
dd 1F4B2A80h, 191F901Ch, 80040269h, 2A004021h
dd 1919C125h, 0FF2614h, 41500090h, 220A3926h
dd 965F3501h, 4021AAE7h, 80018933h, 45141E18h
dd 258A2ADFh, 3143206Bh, 0FFEDEE37h, 2D206E58h
dd 6E75746Dh, 65673D65h, 63697204h, 0B6C3D90Eh
dd 637261FFh, 35693D68h, 670B3638h, 3324F02h
dd 7FA805A8h, 69756266h, 2D12646Ch, 2C5DF504h
dd 6F6E117Ah, 0FB74732Dh, 7CB500DFh, 6365782Dh
dd 726F74h, 2F2E2E0Ch, 6EB1B302h, 2F4F733Bh
dd 2F6E2D26h, 0B7FFEC33h, 63100660h, 6F682F00h
dd 6B2F656Dh, 68746965h, 3B1622Ah, 67306C54h
dd 0CB50083Bh, 632D863Ah, 402EDF64h, 2D73737Dh
dd 6576B66Eh, 646E6177h, 0F60E1F62h, 36786FDEh
dd 7100581Ch, 0B7050415h, 146FB1B7h, 0F4030074h
dd 73E5070Bh, 64E46769h, 0B7B0BF20h, 202147Fh
dd 72787307h, 8152074h, 3F6F6C05h, 476DECF2h
dd 0C100420h, 756F6404h, 0F6E16C62h, 65FE56h
dd 5F041002h, 32317946h, 6010C38h, 145AC528h
dd 0DBE9616Dh, 0DDB1546Bh, 69233492h, 0F766BB6Fh
dd 35BDDEDEh, 1BFC10D2h, 74705F05h, 9D40126h
dd 0DD440D0Ch, 23635DDEh, 9608D501h, 0F6625F35h
dd 512B6465h, 6608D61Ch, 1D67616Ch, 0C8DD6B64h
dd 690E0CD7h, 23D80E76h, 106E739Bh, 3E5A703Ah
dd 6C8C14D9h, 0C00D335Bh, 18DA107Ah, 0BEA219B2h
dd 66706D74h, 9EDB5365h, 1C3EFFB7h, 0A1040600h
dd 4C494607h, 3DC6845h, 0F6F7026Ch, 1A323AEEh
dd 0A000903h, 15EF17ADh, 639C0E0Fh, 5160593h
dd 560704FCh, 22216D68h, 1B60812Eh, 0EF632F73h
dd 0D6F1063h, 65106476h, 0DDBB683Dh, 13705EDEh
dd 0A9626D5Fh, 61067275h, 3ADC2878h, 178E727Eh
dd 5F737973h, 0CA117262h, 0D82F7014h, 9D2B08F7h
dd 851B1C82h, 0BC51ADF3h, 16E33146h, 36E50292h
dd 0DF0AE8D6h, 55BAFA2Eh, 0DBBA7E77h, 0FB0FB192h
dd 116F6A60h, 73C8C2FCh, 0FD6E6940h, 8C2B3E0Bh
dd 6F6DF0DDh, 145B664h, 886F8415h, 761B9B1Fh
dd 3CB16461h, 0E020E0Ch, 0B9B24B3Dh, 3E0E8324h
dd 0D8F6E1DCh, 0E410E9Bh, 61644BFCh, 68679F79h
dd 0DAA0BBDFh, 16015DBBh, 7AC61221h, 65D8386Fh
dd 5E12D56Bh, 77D40160h, 0DF0ED903h, 17FBA67h
dd 338C7A22h, 32E4165Fh, 45036773h, 8727447Eh
dd 0B7F5C9Dh, 6E078033h, 0F40A17B4h, 6C617694h
dd 162A3C4Bh, 0F6B42BDBh, 629A1158h, 752F1116h
dd 15E1EEDDh, 0E67A03E0h, 4BC0D05h, 6F0E03F5h
dd 4EE9ACFh, 2D0FFB14h, 362B7165h, 0EEB20C0Fh
dd 12049F33h, 8267C04h, 0B0B3300Eh, 570AEC91h
dd 746E6FB2h, 7D9BD97Ch, 0CE12BB05h, 17431903h
dd 23FC10BEh, 4C96325h, 100D1E08h, 0B4C16DBh
dd 3C8A72C1h, 0A867B05Fh, 5A1FDB0Bh, 61D155Fh
dd 11060517h, 35B65F9Ah, 0D1D61B9h, 6C2363A9h
dd 0DA37D420h, 657211F6h, 0EB04702Dh, 5F315F78h
dd 433581C9h, 341356EEh, 0C81C9DB7h, 45043803h
dd 0B6D56A6Fh, 0D3159C8h, 9211DF05h, 0AD6D8F58h
dd 5F925922h, 7611070Fh, 0B5B63693h, 24080DB3h
dd 99D74DFh, 0BAE76153h, 9E0469EEh, 3279C32h
dd 1F051C0Fh, 0ED6CD75Ah, 2C0AB45Bh, 3C70DC0Bh
dd 0C1B7D976h, 581A73B6h, 17271A01h, 92EB1876h
dd 4AE5C9Dh, 936108FEh, 71BEEA7Fh, 70A7967h
dd 1AAF10DDh, 0DE070E05h, 0E1D6FB0Fh, 500AF08h
dd 171DDF1Dh, 6866E904h, 430E1885h, 1A09E010h
dd 16D84B9Bh, 2C4B687Ch, 0A2313462h, 0E307A5BEh
dd 0C37547F0h, 0A88E6E76h, 0DC43AD5Fh, 7BD151Bh
dd 0E10DB3B6h, 8E9060Bh, 1B5F0371h, 3880AE3h
dd 9E123901h, 545286DAh, 630A4163h, 7EDC5C6Fh
dd 6052D1BFh, 2108E607h, 64648E0Bh, 0C80DE79Bh
dd 0E59AA056h, 46DBE80Ch, 0F04D761h, 7E2E6669h
dd 5BE91272h, 82326EBh, 14436E42h, 6ED6DDEAh
dd 75DD0C23h, 69AE136Ch, 0BEC7EB12h, 360DE593h
dd 1162100Bh, 52424EDh, 6E95B23h, 90697636h
dd 0F328EE21h, 6F2FB73Dh, 0F6787376h, 0E3C07F0h
dd 0DA9AED7Ah, 8740F148h, 7353657Fh, 37B4326Eh
dd 44F241B2h, 81591222h, 0B4D6C8D8h, 3648F313h
dd 5D23039Eh, 0C461DE43h, 8CFA4CF5h, 11B16F35h
dd 4B0DF66Ch, 57731150h, 773AC78h, 5C12F97Fh
dd 505B6605h, 0B646F676h, 1068FB35h, 7E21FC34h
dd 6C33B064h, 1378FE33h, 0C5786D6Dh, 34C10AC6h
dd 1284355Ah, 9DB74EC3h, 60120136h, 0C9388825h
dd 3B3ED60h, 78139013h, 24053914h, 98F6033Fh
dd 17127913h, 167A139Ch, 6F3E16Ch, 13A00601h
dd 605F65B2h, 846C468Ch, 812A439h, 2F939D36h
dd 91CE746h, 67242CB8h, 300A7C87h, 0DED01DCCh
dd 0E00C193Bh, 4E1520AEh, 6EC392B6h, 0DA3E0B5h
dd 0B0393EF4h, 1BCD39F7h, 6713F80Fh, 16D706B6h
dd 4E106889h, 10176391h, 4F20DD1Ah, 37014FCh
dd 0DB200465h, 1C18F8C7h, 7314015Bh, 25743263h
dd 1232765Bh, 54341904h, 1AB3CB4Bh, 0E16C081Dh
dd 306CEE63h, 14F3295Ch, 57180C33h, 32909939h
dd 16271015h, 65ED1AA8h, 0E17F1974h, 39A3E16Bh
dd 141666D9h, 5619769h, 44A0D61Ah, 0B52674D3h
dd 1556C9CBh, 62181722h, 272D1E72h, 243AC9DBh
dd 661C1916h, 2367339Bh, 200F1A25h, 0C91B0F48h
dd 242730E6h, 0D91C2FDEh, 28CF759Ch, 0F1D5662h
dd 0AD68632Ch, 1EA4E6C4h, 6A717330h, 9832FB9Ah
dd 82341F93h, 0C91122B0h, 38395CD6h, 23101471h
dd 0CAE7C9C9h, 2410723Ch, 4E7BEC40h, 442595BAh
dd 10262161h, 0E4E59395h, 4C276448h, 0CFB39375h
dd 102821A6h, 9C292150h, 889CCE7Dh, 2A229854h
dd 0E5CC5811h, 2B679BE4h, 0E465725Ch, 5B147B64h
dd 602C1614h, 0B4AF9E4Bh, 641A1538h, 1AC9BE42h
dd 1A2630D6h, 0DF30DE68h, 0DA3734D9h, 7063776Ch
dd 96442D79h, 13311DFh, 700B6519h, 0B86A7422h
dd 2211F3CAh, 42CD8574h, 71A8E028h, 102DB50Fh
dd 783464ECh, 2F743021h, 25807270h, 3237C36h
dd 0E0460605h, 0C691CF4h, 0CB043510h, 14DC8321h
dd 24B0B26h, 0C86EC13Bh, 503E6021h, 78354A0Bh
dd 1BB438F0h, 0C7213B9Eh, 3A5FC1B6h, 21187EE5h
dd 60F7C80Bh, 3B1DA88Fh, 15172501h, 0A9C30503h
dd 0A18A1A85h, 935B2E2h, 0BE970037h, 0BFFA1915h
dd 1F582A6Bh, 454E5554h, 4843535Fh, 0C7554445h
dd 80FFFFDBh, 52415013h, 4C414954h, 4745525Fh
dd 5045445Fh, 4E044E45h, 0DAC06C29h, 353F5943h
dd 0BED62553h, 530290BFh, 54494C50h, 61D15323h
dd 57EC76C2h, 47414C46h, 0D545340h, 4CCB1F4Ch
dd 4D21B2FCh, 7E58564Fh, 6FDAC10Fh, 521145B7h
dd 53490659h, 0B354414Dh, 0F77DBD30h, 55460692h
dd 504D436Dh, 5F88415Fh, 0B5915242h, 2405AE52h
dd 0ED21F1BDh, 367E48BDh, 53080034h, 45BDA44Fh
dd 9B21E40h, 554C4126h, 0A12FE56Bh, 434152CEh
dd 0A64D5543h, 0B5A1A40Ah, 54554F7Fh, 4E494F47h
dd 0B00EFDFh, 7F6B5EEh, 4F4C4F52h, 4A085547h
dd 0F253ED1Eh, 0C810B65h, 4950451Eh, 0BC2DD60Dh
dd 41B27F25h, 2C520E14h, 1502D84Ch, 0F842648h
dd 96FB35ACh, 0C51D4C40h, 21D95E16h, 554F44BFh
dd 4F2D1142h, 656E8450h, 152CDB25h, 6C30C413h
dd 3DFD0DADh, 8510546Eh, 250B815h, 0C4E4FCFh
dd 6EDB2E1Dh, 520AD985h, 4A15F84Eh, 0C342F46h
dd 4A5F525Fh, 0CC176355h, 87160054h, 1A6586C2h
dd 28575469h, 9F1ADC1Ch, 454645E1h, 5442FAE4h
dd 8C43490Ch, 2C68592Fh, 434C17ECh, 0AE6F0150h
dd 3518192Dh, 4944FE72h, 85B6346h, 2C19000Bh
dd 429D4349h, 436AD65Bh, 9E11159Fh, 0EDDC31B6h
dd 448A4547h, 456E3146h, 42C01BA7h, 0D6EA4B6Bh
dd 858755F6h, 0D7A4A101h, 7744CA56h, 735BEC04h
dd 446B38C4h, 0BD1D0052h, 2DA19D1Ah, 0F75557B0h
dd 64784D04h, 891F610Fh, 381E1E00h, 0C2561F00h
dd 2E6E70E7h, 435B4F73h, 94B6E0F0h, 0F2962030h
dd 60BB0852h, 2185D25Ah, 47490711h, 618F1909h
dd 2356FB5Fh, 2DBE4560h, 22D82D84h, 4648310Eh
dd 21702300h, 4313C2FFh, 44544Ch, 6B934224h
dd 259FB647h, 196D46A8h, 0B54AC0F0h, 7E42A931h
dd 0DB4322F2h, 0DA44615Ah, 7D4E3B80h, 21ED69Bh
dd 724E2742h, 58076446h, 56C346D8h, 2829537Ah
dd 88575969h, 0E986EB50h, 0BCAC29DCh, 1A0B0190h
dd 0DB46462Ah, 0F32B7480h, 382B0088h, 0D9387D58h
dd 30F78E0Ah, 6A373833h, 2CFCE521h, 2E3AB3ACh
dd 0B3524D47h, 0B689E53h, 0A8491BABh, 0ED07B32Dh
dd 51430AD1h, 820AD13Eh, 0B64236DAh, 672E2541h
dd 23DE504Fh, 2F26C981h, 234B4326h, 137B2642h
dd 3029FBC1h, 0F02B5ACDh, 22445954h, 0F85B4F09h
dd 31B7B616h, 70308B1Eh, 17725159h, 1E586DC6h
dd 52CA3200h, 9B42C78Eh, 15C64D51h, 63ED56FAh
dd 33590217h, 4D4F3822h, 76D33424h, 0BA72048h
dd 40E3D253h, 35863640h, 21A1AACCh, 50460BD8h
dd 9D36682Ch, 0B7590C8h, 3721545Eh, 12C9A486h
dd 502F381Eh, 0B7E32385h, 4246555Eh, 34833900h
dd 0FB642E05h, 492654ACh, 3A554558h, 0B7646247h
dd 4E487905h, 0BB353B00h, 62152A55h, 4157BCECh
dd 0C211D649h, 1E3CAC0Fh, 36353258h, 210BBF6h
dd 0F9283DD9h, 264A293Eh, 436E0973h, 70253B3Fh
dd 65401958h, 5BE4957h, 5D57EC06h, 4C344100h
dd 7099D18h, 6AB55986h, 695FDF03h, 0E21DB2D2h
dd 71204200h, 961014FCh, 435C41DAh, 5A159747h
dd 315559A0h, 835A2AC5h, 45953899h, 4E6BB027h
dd 2C1848DAh, 54239A45h, 496CB25Bh, 4655A592h
dd 4F02083h, 7AE053h, 0B51A7C47h, 81554B56h
dd 0D0B0273Fh, 4CC2425h, 7A49EF31h, 7EA3A4BDh
dd 4F4E49BBh, 58BA402Dh, 9549235Ah, 724A8442h
dd 0EAB02765h, 8B51A34Bh, 8128D601h, 821F74BDh
dd 0D04D392Dh, 264E003Eh, 0D4191851h, 0E36367F2h
dd 4F4E3A42h, 83473058h, 6C2DDD85h, 30291450h
dd 46C75100h, 0CD8CD8C6h, 927B5290h, 0E93041CFh
dd 0A2531E84h, 3EC59870h, 0ECB93A50h, 0A64345CBh
dd 51B754B4h, 1B2B906h, 5651E955h, 4044CD0h
dd 0CC725905h, 0E8FD3425h, 0A505055h, 0C84CBE57h
dd 7DA546E5h, 0CE04586Dh, 668CD515h, 31495734h
dd 0B6D1FD1Eh, 720761BDh, 16019F32h, 0D032322Ch
dd 4DC44D8Ch, 3F9042B8h, 75060222h, 0DAC6AE16h
dd 0B81EC2E1h, 2C3E500Fh, 0CA616CB8h, 2523812h
dd 1A055814h, 3EFFB2Fh, 0EF53420Fh, 0D8C9EAD7h
dd 0B61004B2h, 7D168505h, 4E49B2D9h, 2CB69A0Bh
dd 43001602h, 0B95F780h, 0FE09B41Ah, 1908AD95h
dd 5F16403Bh, 1B96F64h, 756039ADh, 0AA041F9Eh
dd 57AD676Dh, 2D6D2F04h, 0EB6AE06Eh, 59665F9Eh
dd 16E50D02h, 1E1505BBh, 0AC9F967h, 0F8E46051h
dd 0EC06052Ah, 84DA2E18h, 97BF682h, 0FCFCEDB7h
dd 644E67Dh, 3431102h, 0A3C54211h, 4702BE57h
dd 0B307051Ch, 9ACED1B1h, 270735ECh, 0A3AC4276h
dd 0CE16B59h, 8518A10h, 0EE1ACD1Dh, 0C095909h
dd 0B0A545Ah, 0D57212ADh, 0D60442EBh, 689D18D4h
dd 586E4949h, 0D4AB570Ch, 0F3393768h, 1C0C0D18h
dd 0E4260D3Dh, 1C061AD7h, 37A7F20h, 1C99F27Ah
dd 530C0FDFh, 100FFA83h, 0AE520DA2h, 0A7119EEAh
dd 76A67D9Bh, 1CDFA352h, 2564DD12h, 165EF433h
dd 590AFB21h, 0E80BB03Bh, 151A5645h, 996853EBh
dd 0D153D0C9h, 9C8619ACh, 0EFB5516Dh, 76188B58h
dd 1CC9B2D9h, 1A149019h, 0B9053395h, 181B106Ch
dd 980C96FEh, 1D1F1C39h, 0CB942EF6h, 4B2E1E77h
dd 2610A65Fh, 1F726F43h, 1D525A0Bh, 34B2EF7Ah
dd 0AB3212Ch, 0B18EAE2Ah, 4375981Ch, 930F5374h
dd 2385C027h, 0A016EBC9h, 0D80A1901h, 1450B740h
dd 627D18F1h, 701BDE78h, 616D1B12h, 12083D6Dh
dd 6B219025h, 1B5D19F5h, 595C9C3Eh, 7276737Bh
dd 153F3A1Ah, 524F8C3Fh, 70797455h, 8DA7465h
dd 5CB83006h, 0F81C9934h, 0E34E2643h, 0E922B584h
dd 33491336h, 0C0E6B0C6h, 34102E5Ah, 0A9473502h
dd 68501956h, 57349F81h, 0EA1332DBh, 0E617394Bh
dd 0AD732970h, 16BC1028h, 531CCB1Ah, 2B14C934h
dd 1A399713h, 12D241C4h, 18941B43h, 0D3324730h
dd 0E7B4524h, 0AB6B6406h, 7E530979h, 0DB68E65Bh
dd 44C54259h, 2917E9CCh, 56C0D603h, 0BF54503h
dd 34284213h, 4E4FE7B0h, 0C03F0C4Eh, 0B98C80EDh
dd 4B0DBB3Ch, 0C81E264Eh, 0F0EB096h, 594B0F76h
dd 0F4CCA44Fh, 0A21302F3h, 0A665CA35h, 0A510BD12h
dd 8C206D43h, 12319199h, 64CC075Bh, 2A1378E8h
dd 1A201449h, 0AED72665h, 309F9C53h, 0DB08481Ah
dd 159D68A1h, 0C0C2C8C8h, 0AF16163Eh, 1C9917B3h
dd 0A1FB0818h, 0F2075641h, 382180h, 1BCA4D19h
dd 3B74C10h, 303E3031h, 0B6C7B44h, 4031A999h
dd 121CDC12h, 8F9230B6h, 0E11D0033h, 646D4B1Eh
dd 1F540723h, 8C964B12h, 2520B01Ch, 52214E5Ah
dd 0B4A1E0C0h, 0D9066122h, 1F9C092h, 0BD5B1C09h
dd 0A8510212h, 38B50303h, 5EAB7B6Dh, 625F0455h
dd 2764366Fh, 10BD3B30h, 150909B8h, 994C260Bh
dd 638D6EA9h, 0A25A56Fh, 9C0FA4BCh, 1CB3A308h
dd 4F1CA3B1h, 72C9808Ah, 90D72CBh, 0BD52A2C0h
dd 737A211Dh, 712A4707h, 7A555507h, 24317B09h
dd 39B6554Bh, 0A607CBDDh, 0E5AA427Ah, 0C4660404h
dd 75DF61D5h, 70920322h, 2078656Ch, 58720410h
dd 1AE921B2h, 1C921811h, 16521B36h, 0DB97220h
dd 0EDCA1AABh, 501D7E1Ch, 0FF0CBA8Eh, 0A92E1D6Eh
dd 3CBB8476h, 8AF66370h, 0C89D0062h, 16766DB3h
dd 7AE1177Eh, 83020212h, 7EDAAFFh, 35632466h
dd 0BF102A0Ah, 0D523D91Dh, 5C5EEE6h, 0D1AE0817h
dd 0D65F331Dh, 0A3162341h, 0E5F00CAh, 0AB6E7481h
dd 1517C6C7h, 0DFFA0244h, 321830C8h, 0A09390Bh
dd 0CF800305h, 0E5195B3h, 3D8C3AE7h, 0C8AA306h
dd 0B06F3C2Ch, 0DA158140h, 0E038A01h, 8BFFD31Bh
dd 0E250EFBh, 1130513h, 0B130825h, 81B0803h
dd 520A1710h, 2442EE4Dh, 0E3E0BEEh, 0C6CF261Ah
dd 13D0D6DBh, 82E138Bh, 3B0B3A13h, 4102B516h
dd 10010BEEh, 0BAE710FDh, 1F0E9B62h, 330FB238h
dd 5135A2Ah, 191607ECh, 0F06018Ch, 31FD5758h
dd 34302109h, 3C193F1Ch, 5EC192EDh, 0C051213h
dd 0DF67B12Ah, 0D2F546Ch, 19270115h, 88050E3Eh
dd 0B5B99AF6h, 108D8F0Fh, 916F9F04h, 5E6BAC64h
dd 341C2811h, 0B005AB12h, 13B90643h, 0CF101405h
dd 59B6426h, 36051550h, 6E961716h, 178E33EBh
dd 18A8276Eh, 4A284047h, 56DB1EC1h, 28D814h
dd 24A2A305h, 9BE66B05h, 26D9Bh, 0FB010149h
dd 0C000D0Eh, 0DC824891h, 77A8202h, 661702FDh
dd 692F6769h, 79630081h, 77B74167h, 532E3D01h
dd 2050037h, 76DFFB6Dh, 498E0345h, 4B592222h
dd 593D6730h, 0B3E3659h, 0DDBF200Ah, 535E0102h
dd 14D7001h, 9014120h, 6E28ADCBh, 77B2C5h
dd 0B990756Ch, 96FD5645h, 6C8D2817h, 3423BD95h
dd 2DFEF7D2h, 73AB3091h, 6F696474h, 0AB6682Eh
dd 399E80E6h, 65670B15h, 66800B12h, 9986806h
dd 6DF28A3Ah, 22617411h, 0CE2D8F02h, 0FC28FF74h
dd 73746E61h, 68710313h, 9749DD6h, 73422D04h
dd 0DD37150Eh, 55CE72Ch, 802D6C62h, 8873E4B6h
dd 818D051Bh, 0F389280Ah, 0DB34141Ch, 0FF000010h
dd 0E5105101h, 204F0A0Ch, 5C4C141Dh, 8C81A20Bh
dd 80376DB8h, 0C0096603h, 15C10408h, 0A2A10901h
dd 64A8A0DFh, 12047041h, 422FE430h, 0E3121882h
dd 105DDB72h, 53415609h, 3333620h, 31E2CA8Ah
dd 0E549312Eh, 654505h, 0FF140058h, 7138D04Bh
dd 6C65447Ch, 43657465h, 15736972h, 61564BF4h
dd 6365536Ch, 0ECAE16D6h, 154A5104h, 20C5B078h
dd 0B75010D8h, 66DE460Ch, 432851BFh, 65736F6Ch
dd 7372030Ah, 0D9F64874h, 414D04D6h, 78654E0Fh
dd 5F014D0Eh, 694C8028h, 1B77262h, 0B7C16B6Fh
dd 6F436E47h, 120D6D6Dh, 0B63E1D6Eh, 4C1076DDh
dd 72453A61h, 4D0D7258h, 0D175646Fh, 37DB9EF7h
dd 113D2148h, 0DCDD4173h, 77C700EEh, 94956E49h
dd 457A69h, 4CB595FBh, 15766165h, 16B05D2Fh
dd 534E7EE6h, 73686E55h, 5C636B6Fh, 70CACF64h
dd 0C8EFA824h, 1C9BDD6Dh, 6E736C54h, 0D5753C56h
dd 80CE80B1h, 0C29D505Dh, 0F64A203h, 2B5A416Dh
dd 9065CD3Fh, 0CF675F5Fh, 900606CCh, 9E675FDBh
dd 7B5EC5C7h, 2700DEBh, 3A766E65h, 0E5F00D89h
dd 365D007Bh, 70615F73h, 0EE686770h, 8A0FFF44h
dd 735E075Dh, 725D37BBh, 66076F6Eh, 922EF70h
dd 17150AE6h, 1A706C0Eh, 5AC1AB0Ah, 562DFB0h
dd 55346373h, 0DCCF0A35h, 321170B0h, 4F626160h
dd 0E6B3400Ch, 35213719h, 15ACE19Dh, 660D0745h
dd 0A2770592h, 2B0CEB05h, 0B91B6D07h, 0A1770A24h
dd 0C56377E1h, 6EEDCD44h, 0D78301EDh, 75076674h
dd 9C341574h, 2860B42Bh, 6B15407Fh, 0E6B81033h
dd 2942130Eh, 0A2095908h, 7274075Dh, 0DAD60842h
dd 6E17B6C7h, 6D636E07h, 2B590870h, 0C3EC3735h
dd 66766477h, 5156A55h, 74C13917h, 0FE2F844Dh
dd 0B3B163B7h, 4A690870h, 3455000h, 20D014Ch
dd 0EFFF3h, 5DDAF8C8h, 7A00h, 0D26501E0h
dd 0BF4413Dh, 5F200201h, 0CE02034Ch, 0D0E08D36h
dd 40DD12h, 0C5441004h, 417CE88h, 0EC76D96Ch
dd 120CE64h, 777220Ch, 0D9B21003h, 42BB37Bh
dd 0BD000907h, 80EEA322h, 4EC060Fh, 0E592A0h
dd 381837B2h, 0ED9BE881h, 0BE2E061Ah, 2D940774h
dd 430BEB90h, 6093D452h, 26F6601Dh, 642EC2DDh
dd 18F661E8h, 7D9E27F3h, 1632C85Bh, 722EC030h
dd 9E051428h, 27E9A692h, 40340650h, 0A692342Fh
dd 0D860CF3Bh, 3A0A2709h, 0B850CD9Eh, 0C3BEBD2Eh
dd 0E4C27070h, 778040BBh, 200F4369h, 9F80374Dh
dd 52434408h, 0E4190054h, 90C700B0h, 0DF3C834Ch
dd 27737946h, 0E44EA020h, 2F257B3Bh, 2738C831h
dd 23F91CB0h, 42405019h, 4239322Fh, 0D91CB1Eh
dd 5258C0D6h, 0D8341027h, 31B1CD20h, 0E001494Fh
dd 9E412772h, 35350391h, 658FF0C8h, 36749007h
dd 23A19F37h, 0C77C94B7h, 30384F76h, 27256F97h
dd 110009Bh, 6801B78h, 0B1007C04h, 7, 40000000h
dd 0FF02h, 3 dup(0)



public start
start proc near

var_B8= byte ptr -0B8h

pusha
mov     esi, offset byte_410015
lea     edi, [esi-0F015h]
push    edi
jmp     short loc_4133AA
align 10h

loc_4133A0:
mov     al, [esi]
inc     esi
mov     [edi], al
inc     edi

loc_4133A6:
add     ebx, ebx
jnz     short loc_4133B1

loc_4133AA:
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx

loc_4133B1:
jb      short loc_4133A0
mov     eax, 1

loc_4133B8:
add     ebx, ebx
jnz     short loc_4133C3
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx

loc_4133C3:
adc     eax, eax
add     ebx, ebx
jnb     short loc_4133B8
jnz     short loc_4133D4
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx
jnb     short loc_4133B8

loc_4133D4:
xor     ecx, ecx
sub     eax, 3
jb      short loc_4133E8
shl     eax, 8
mov     al, [esi]
inc     esi
xor     eax, 0FFFFFFFFh
jz      short loc_41345A
mov     ebp, eax

loc_4133E8:
add     ebx, ebx
jnz     short loc_4133F3
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx

loc_4133F3:
adc     ecx, ecx
add     ebx, ebx
jnz     short loc_413400
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx

loc_413400:
adc     ecx, ecx
jnz     short loc_413424
inc     ecx

loc_413405:
add     ebx, ebx
jnz     short loc_413410
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx

loc_413410:
adc     ecx, ecx
add     ebx, ebx
jnb     short loc_413405
jnz     short loc_413421
mov     ebx, [esi]
sub     esi, 0FFFFFFFCh
adc     ebx, ebx
jnb     short loc_413405

loc_413421:
add     ecx, 2

loc_413424:
cmp     ebp, 0FFFFF300h
adc     ecx, 1
lea     edx, [edi+ebp]
cmp     ebp, 0FFFFFFFCh
jbe     short loc_413444

loc_413435:
mov     al, [edx]
inc     edx
mov     [edi], al
inc     edi
dec     ecx
jnz     short loc_413435
jmp     loc_4133A6
align 4

loc_413444:
mov     eax, [edx]
add     edx, 4
mov     [edi], eax
add     edi, 4
sub     ecx, 4
ja      short loc_413444
add     edi, ecx
jmp     loc_4133A6

loc_41345A:
pop     esi
mov     edi, esi
mov     ecx, 119h

loc_413462:
mov     al, [edi]
inc     edi
sub     al, 0E8h

loc_413467:
cmp     al, 1
ja      short loc_413462
cmp     byte ptr [edi], 2
jnz     short loc_413462
mov     eax, [edi]
mov     bl, [edi+4]
shr     ax, 8
rol     eax, 10h
xchg    al, ah
sub     eax, edi
sub     bl, 0E8h
add     eax, esi
mov     [edi], eax
add     edi, 5
mov     al, bl
loop    loc_413467
lea     edi, [esi+11000h]

loc_413494:
mov     eax, [edi]
or      eax, eax
jz      short loc_4134D6
mov     ebx, [edi+4]
lea     eax, [eax+esi+13000h]
add     ebx, esi
push    eax
add     edi, 8
call    dword ptr [esi+1303Ch]
xchg    eax, ebp

loc_4134B1:
mov     al, [edi]
inc     edi
or      al, al
jz      short loc_413494
mov     ecx, edi
push    edi
dec     eax
repne scasb
push    ebp
call    dword ptr [esi+13044h]
or      eax, eax
jz      short loc_4134D0
mov     [ebx], eax
add     ebx, 4
jmp     short loc_4134B1

loc_4134D0:
call    dword ptr [esi+13040h]

loc_4134D6:
mov     ebp, [esi+13048h]
lea     edi, [esi-1000h]
mov     ebx, 1000h
push    eax
push    esp
push    4
push    ebx
push    edi
call    ebp
lea     eax, [edi+19Fh]
and     byte ptr [eax], 7Fh
and     byte ptr [eax+28h], 7Fh
pop     eax
push    eax
push    esp
push    eax
push    ebx
push    edi
call    ebp
pop     eax
lea     ebx, [esi-1000h]
lea     edi, [ebx+13531h]
push    edi
xor     eax, eax
stosb
pop     ecx
dec     ecx
push    eax
push    1
push    ebx
call    ecx
popa
lea     eax, [esp+38h+var_B8]

loc_413522:
push    0
cmp     esp, eax
jnz     short loc_413522
sub     esp, 0FFFFFF80h
jmp     near ptr dword_4012D0
start endp ; sp-analysis failed




public TlsCallback_0
TlsCallback_0 proc near

arg_8= dword ptr  0Ch

jmp     short locret_41354C
push    esi
mov     esi, 409004h
cld

loc_413539:
lodsd
test    eax, eax
jz      short loc_41354B
push    3
pop     ecx

loc_413541:
push    [esp+4+arg_8]
loop    loc_413541
call    eax
jmp     short loc_413539

loc_41354B:
pop     esi

locret_41354C:
retn    0Ch
TlsCallback_0 endp ; sp-analysis failed

align 10h
TlsDirectory dd offset TlsStart
TlsEnd_ptr dd offset TlsEnd
TlsIndex_ptr dd offset TlsIndex
TlsCallbacks_ptr dd offset TlsCallbacks
TlsSizeOfZeroFill dd 0
TlsCharacteristics dd 0
TlsStart dd 1000000h, 1C0040A0h, 380040A0h, 4004070h
dd 4090h, 0
db 3 dup(0)
TlsEnd db 0
TlsCallbacks dd offset TlsCallback_0
dd 0
align 80h
dd 280h dup(?)
UPX1 ends

; Section 3. (virtual address 00014000)
; Virtual size                  : 00001000 (   4096.)
; Section size in file          : 00000200 (    512.)
; Offset to raw data for section: 00003800
; Flags C0000040: Data Readable Writable
; Alignment     : default

; Segment type: Pure data
; Segment permissions: Read/Write
UPX2 segment para public 'DATA' use32
assume cs:UPX2
;org 414000h
__IMPORT_DESCRIPTOR_KERNEL32 dd 0 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aKernel32Dll     ; DLL Name
dd rva LoadLibraryA     ; Import Address Table
__IMPORT_DESCRIPTOR_msvcrt dd 0 ; Import Name Table
dd 0                    ; Time stamp
dd 0                    ; Forwarder Chain
dd rva aMsvcrtDll       ; DLL Name
dd rva _iob             ; Import Address Table
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
db    0
UPX2 ends

;
; Imports from KERNEL32.DLL
;

; Segment type: Externs
; _idata
; HMODULE __stdcall LoadLibraryA(LPCSTR lpLibFileName)
extrn LoadLibraryA:dword
; void __stdcall __noreturn ExitProcess(UINT uExitCode)
extrn ExitProcess:dword
; FARPROC __stdcall GetProcAddress(HMODULE hModule, LPCSTR lpProcName)
extrn GetProcAddress:dword
; BOOL __stdcall VirtualProtect(LPVOID lpAddress, SIZE_T dwSize, DWORD flNewProtect, PDWORD lpflOldProtect)
extrn VirtualProtect:dword

;
; Imports from msvcrt.dll
;
extrn _iob:dword


; Segment type: Pure data
; Segment permissions: Read/Write
UPX2 segment para public 'DATA' use32
assume cs:UPX2
;org 414054h
align 8
aKernel32Dll db 'KERNEL32.DLL',0
aMsvcrtDll db 'msvcrt.dll',0
dw 0
db 'ExitProcess',0
dw 0
db 'GetProcAddress'
dw 0
db 'LoadLibraryA',0
align 2
db 'VirtualProtect',0
align 2
db '_iob',0
align 1000h
UPX2 ends


end start
